<?php //Argentina
$country = 'argentina';

$attr = [
	'levels' => [
		2 => 'Provincias',
		3 => 'Localidades'
	]
];

//Provincias
$data[2] = [
	['argentina','buenos aires',''],
	['argentina','buenos aires-gba',''],
	['argentina','capital federal',''],
	['argentina','catamarca',''],
	['argentina','chaco',''],
	['argentina','chubut',''],
	['argentina','córdoba',''],
	['argentina','corrientes',''],
	['argentina','entre ríos',''],
	['argentina','formosa',''],
	['argentina','jujuy',''],
	['argentina','la pampa',''],
	['argentina','la rioja',''],
	['argentina','mendoza',''],
	['argentina','misiones',''],
	['argentina','neuquén',''],
	['argentina','río negro',''],
	['argentina','salta',''],
	['argentina','san juan',''],
	['argentina','san luis',''],
	['argentina','santa cruz',''],
	['argentina','santa fe',''],
	['argentina','santiago del estero',''],
	['argentina','tierra del fuego',''],
	['argentina','tucumán',''],
];

//Localidades
$data[3] = [
	['buenos aires','25 de mayo',''],
	['buenos aires','3 de febrero',''],
	['buenos aires','a. alsina',''],
	['buenos aires','a. gonzáles cháves',''],
	['buenos aires','aguas verdes',''],
	['buenos aires','alberti',''],
	['buenos aires','arrecifes',''],
	['buenos aires','ayacucho',''],
	['buenos aires','azul',''],
	['buenos aires','bahía blanca',''],
	['buenos aires','balcarce',''],
	['buenos aires','baradero',''],
	['buenos aires','benito juárez',''],
	['buenos aires','berisso',''],
	['buenos aires','bolívar',''],
	['buenos aires','bragado',''],
	['buenos aires','brandsen',''],
	['buenos aires','campana',''],
	['buenos aires','cañuelas',''],
	['buenos aires','capilla del señor',''],
	['buenos aires','capitán sarmiento',''],
	['buenos aires','carapachay',''],
	['buenos aires','carhue',''],
	['buenos aires','cariló',''],
	['buenos aires','carlos casares',''],
	['buenos aires','carlos tejedor',''],
	['buenos aires','carmen de areco',''],
	['buenos aires','carmen de patagones',''],
	['buenos aires','castelli',''],
	['buenos aires','chacabuco',''],
	['buenos aires','chascomús',''],
	['buenos aires','chivilcoy',''],
	['buenos aires','colón',''],
	['buenos aires','coronel dorrego',''],
	['buenos aires','coronel pringles',''],
	['buenos aires','coronel rosales',''],
	['buenos aires','coronel suarez',''],
	['buenos aires','costa azul',''],
	['buenos aires','costa chica',''],
	['buenos aires','costa del este',''],
	['buenos aires','costa esmeralda',''],
	['buenos aires','daireaux',''],
	['buenos aires','darregueira',''],
	['buenos aires','del viso',''],
	['buenos aires','dolores',''],
	['buenos aires','don torcuato',''],
	['buenos aires','ensenada',''],
	['buenos aires','escobar',''],
	['buenos aires','exaltación de la cruz',''],
	['buenos aires','florentino ameghino',''],
	['buenos aires','garín',''],
	['buenos aires','gral. alvarado',''],
	['buenos aires','gral. alvear',''],
	['buenos aires','gral. arenales',''],
	['buenos aires','gral. belgrano',''],
	['buenos aires','gral. guido',''],
	['buenos aires','gral. lamadrid',''],
	['buenos aires','gral. las heras',''],
	['buenos aires','gral. lavalle',''],
	['buenos aires','gral. madariaga',''],
	['buenos aires','gral. pacheco',''],
	['buenos aires','gral. paz',''],
	['buenos aires','gral. pinto',''],
	['buenos aires','gral. pueyrredón',''],
	['buenos aires','gral. rodríguez',''],
	['buenos aires','gral. viamonte',''],
	['buenos aires','gral. villegas',''],
	['buenos aires','guaminí',''],
	['buenos aires','guernica',''],
	['buenos aires','hipólito yrigoyen',''],
	['buenos aires','ing. maschwitz',''],
	['buenos aires','junín',''],
	['buenos aires','la plata',''],
	['buenos aires','laprida',''],
	['buenos aires','las flores',''],
	['buenos aires','las toninas',''],
	['buenos aires','leandro n. alem',''],
	['buenos aires','lincoln',''],
	['buenos aires','loberia',''],
	['buenos aires','lobos',''],
	['buenos aires','los cardales',''],
	['buenos aires','los toldos',''],
	['buenos aires','lucila del mar',''],
	['buenos aires','luján',''],
	['buenos aires','magdalena',''],
	['buenos aires','maipú',''],
	['buenos aires','mar chiquita',''],
	['buenos aires','mar de ajó',''],
	['buenos aires','mar de las pampas',''],
	['buenos aires','mar del plata',''],
	['buenos aires','mar del tuyú',''],
	['buenos aires','marcos paz',''],
	['buenos aires','mercedes',''],
	['buenos aires','miramar',''],
	['buenos aires','monte',''],
	['buenos aires','monte hermoso',''],
	['buenos aires','munro',''],
	['buenos aires','navarro',''],
	['buenos aires','necochea',''],
	['buenos aires','olavarría',''],
	['buenos aires','partido de la costa',''],
	['buenos aires','pehuajó',''],
	['buenos aires','pellegrini',''],
	['buenos aires','pergamino',''],
	['buenos aires','pigüé',''],
	['buenos aires','pila',''],
	['buenos aires','pilar',''],
	['buenos aires','pinamar',''],
	['buenos aires','pinar del sol',''],
	['buenos aires','polvorines',''],
	['buenos aires','pte. perón',''],
	['buenos aires','puán',''],
	['buenos aires','punta indio',''],
	['buenos aires','ramallo',''],
	['buenos aires','rauch',''],
	['buenos aires','rivadavia',''],
	['buenos aires','rojas',''],
	['buenos aires','roque pérez',''],
	['buenos aires','saavedra',''],
	['buenos aires','saladillo',''],
	['buenos aires','salliqueló',''],
	['buenos aires','salto',''],
	['buenos aires','san andrés de giles',''],
	['buenos aires','san antonio de areco',''],
	['buenos aires','san antonio de padua',''],
	['buenos aires','san bernardo',''],
	['buenos aires','san cayetano',''],
	['buenos aires','san clemente del tuyú',''],
	['buenos aires','san nicolás',''],
	['buenos aires','san pedro',''],
	['buenos aires','san vicente',''],
	['buenos aires','santa teresita',''],
	['buenos aires','suipacha',''],
	['buenos aires','tandil',''],
	['buenos aires','tapalqué',''],
	['buenos aires','tordillo',''],
	['buenos aires','tornquist',''],
	['buenos aires','trenque lauquen',''],
	['buenos aires','tres lomas',''],
	['buenos aires','villa gesell',''],
	['buenos aires','villarino',''],
	['buenos aires','zárate',''],
	['buenos aires-gba','11 de septiembre',''],
	['buenos aires-gba','20 de junio',''],
	['buenos aires-gba','25 de mayo',''],
	['buenos aires-gba','acassuso',''],
	['buenos aires-gba','adrogué',''],
	['buenos aires-gba','aldo bonzi',''],
	['buenos aires-gba','área reserva cinturón ecológico',''],
	['buenos aires-gba','avellaneda',''],
	['buenos aires-gba','banfield',''],
	['buenos aires-gba','barrio parque',''],
	['buenos aires-gba','barrio santa teresita',''],
	['buenos aires-gba','beccar',''],
	['buenos aires-gba','bella vista',''],
	['buenos aires-gba','berazategui',''],
	['buenos aires-gba','bernal este',''],
	['buenos aires-gba','bernal oeste',''],
	['buenos aires-gba','billinghurst',''],
	['buenos aires-gba','boulogne',''],
	['buenos aires-gba','burzaco',''],
	['buenos aires-gba','carapachay',''],
	['buenos aires-gba','caseros',''],
	['buenos aires-gba','castelar',''],
	['buenos aires-gba','churruca',''],
	['buenos aires-gba','ciudad evita',''],
	['buenos aires-gba','ciudad madero',''],
	['buenos aires-gba','ciudadela',''],
	['buenos aires-gba','claypole',''],
	['buenos aires-gba','crucecita',''],
	['buenos aires-gba','dock sud',''],
	['buenos aires-gba','don bosco',''],
	['buenos aires-gba','don orione',''],
	['buenos aires-gba','el jagüel',''],
	['buenos aires-gba','el libertador',''],
	['buenos aires-gba','el palomar',''],
	['buenos aires-gba','el tala',''],
	['buenos aires-gba','el trébol',''],
	['buenos aires-gba','ezeiza',''],
	['buenos aires-gba','ezpeleta',''],
	['buenos aires-gba','florencio varela',''],
	['buenos aires-gba','florida',''],
	['buenos aires-gba','francisco álvarez',''],
	['buenos aires-gba','gerli',''],
	['buenos aires-gba','glew',''],
	['buenos aires-gba','gonzález catán',''],
	['buenos aires-gba','gral. lamadrid',''],
	['buenos aires-gba','grand bourg',''],
	['buenos aires-gba','gregorio de laferrere',''],
	['buenos aires-gba','guillermo enrique hudson',''],
	['buenos aires-gba','haedo',''],
	['buenos aires-gba','hurlingham',''],
	['buenos aires-gba','ing. sourdeaux',''],
	['buenos aires-gba','isidro casanova',''],
	['buenos aires-gba','ituzaingó',''],
	['buenos aires-gba','josé c. paz',''],
	['buenos aires-gba','josé ingenieros',''],
	['buenos aires-gba','josé marmol',''],
	['buenos aires-gba','la lucila',''],
	['buenos aires-gba','la reja',''],
	['buenos aires-gba','la tablada',''],
	['buenos aires-gba','lanús',''],
	['buenos aires-gba','llavallol',''],
	['buenos aires-gba','loma hermosa',''],
	['buenos aires-gba','lomas de zamora',''],
	['buenos aires-gba','lomas del millón',''],
	['buenos aires-gba','lomas del mirador',''],
	['buenos aires-gba','longchamps',''],
	['buenos aires-gba','los polvorines',''],
	['buenos aires-gba','luis guillón',''],
	['buenos aires-gba','malvinas argentinas',''],
	['buenos aires-gba','martín coronado',''],
	['buenos aires-gba','martínez',''],
	['buenos aires-gba','merlo',''],
	['buenos aires-gba','ministro rivadavia',''],
	['buenos aires-gba','monte chingolo',''],
	['buenos aires-gba','monte grande',''],
	['buenos aires-gba','moreno',''],
	['buenos aires-gba','morón',''],
	['buenos aires-gba','muñiz',''],
	['buenos aires-gba','olivos',''],
	['buenos aires-gba','pablo nogués',''],
	['buenos aires-gba','pablo podestá',''],
	['buenos aires-gba','paso del rey',''],
	['buenos aires-gba','pereyra',''],
	['buenos aires-gba','piñeiro',''],
	['buenos aires-gba','plátanos',''],
	['buenos aires-gba','pontevedra',''],
	['buenos aires-gba','quilmes',''],
	['buenos aires-gba','rafael calzada',''],
	['buenos aires-gba','rafael castillo',''],
	['buenos aires-gba','ramos mejía',''],
	['buenos aires-gba','ranelagh',''],
	['buenos aires-gba','remedios de escalada',''],
	['buenos aires-gba','sáenz peña',''],
	['buenos aires-gba','san antonio de padua',''],
	['buenos aires-gba','san fernando',''],
	['buenos aires-gba','san francisco solano',''],
	['buenos aires-gba','san isidro',''],
	['buenos aires-gba','san josé',''],
	['buenos aires-gba','san justo',''],
	['buenos aires-gba','san martín',''],
	['buenos aires-gba','san miguel',''],
	['buenos aires-gba','santos lugares',''],
	['buenos aires-gba','sarandí',''],
	['buenos aires-gba','sourigues',''],
	['buenos aires-gba','tapiales',''],
	['buenos aires-gba','temperley',''],
	['buenos aires-gba','tigre',''],
	['buenos aires-gba','tortuguitas',''],
	['buenos aires-gba','tristán suárez',''],
	['buenos aires-gba','trujui',''],
	['buenos aires-gba','turdera',''],
	['buenos aires-gba','valentín alsina',''],
	['buenos aires-gba','vicente lópez',''],
	['buenos aires-gba','villa adelina',''],
	['buenos aires-gba','villa ballester',''],
	['buenos aires-gba','villa bosch',''],
	['buenos aires-gba','villa caraza',''],
	['buenos aires-gba','villa celina',''],
	['buenos aires-gba','villa centenario',''],
	['buenos aires-gba','villa de mayo',''],
	['buenos aires-gba','villa diamante',''],
	['buenos aires-gba','villa domínico',''],
	['buenos aires-gba','villa españa',''],
	['buenos aires-gba','villa fiorito',''],
	['buenos aires-gba','villa guillermina',''],
	['buenos aires-gba','villa insuperable',''],
	['buenos aires-gba','villa josé león suárez',''],
	['buenos aires-gba','villa la florida',''],
	['buenos aires-gba','villa luzuriaga',''],
	['buenos aires-gba','villa martelli',''],
	['buenos aires-gba','villa obrera',''],
	['buenos aires-gba','villa progreso',''],
	['buenos aires-gba','villa raffo',''],
	['buenos aires-gba','villa sarmiento',''],
	['buenos aires-gba','villa tesei',''],
	['buenos aires-gba','villa udaondo',''],
	['buenos aires-gba','virrey del pino',''],
	['buenos aires-gba','wilde',''],
	['buenos aires-gba','william morris',''],
	['capital federal','agronomía',''],
	['capital federal','almagro',''],
	['capital federal','balvanera',''],
	['capital federal','barracas',''],
	['capital federal','belgrano',''],
	['capital federal','boca',''],
	['capital federal','boedo',''],
	['capital federal','caballito',''],
	['capital federal','chacarita',''],
	['capital federal','coghlan',''],
	['capital federal','colegiales',''],
	['capital federal','constitución',''],
	['capital federal','flores',''],
	['capital federal','floresta',''],
	['capital federal','la paternal',''],
	['capital federal','liniers',''],
	['capital federal','mataderos',''],
	['capital federal','monserrat',''],
	['capital federal','monte castro',''],
	['capital federal','nueva pompeya',''],
	['capital federal','núñez',''],
	['capital federal','palermo',''],
	['capital federal','parque avellaneda',''],
	['capital federal','parque chacabuco',''],
	['capital federal','parque chas',''],
	['capital federal','parque patricios',''],
	['capital federal','puerto madero',''],
	['capital federal','recoleta',''],
	['capital federal','retiro',''],
	['capital federal','saavedra',''],
	['capital federal','san cristóbal',''],
	['capital federal','san nicolás',''],
	['capital federal','san telmo',''],
	['capital federal','vélez sársfield',''],
	['capital federal','versalles',''],
	['capital federal','villa crespo',''],
	['capital federal','villa del parque',''],
	['capital federal','villa devoto',''],
	['capital federal','villa gral. mitre',''],
	['capital federal','villa lugano',''],
	['capital federal','villa luro',''],
	['capital federal','villa ortúzar',''],
	['capital federal','villa pueyrredón',''],
	['capital federal','villa real',''],
	['capital federal','villa riachuelo',''],
	['capital federal','villa santa rita',''],
	['capital federal','villa soldati',''],
	['capital federal','villa urquiza',''],
	['catamarca','aconquija',''],
	['catamarca','ancasti',''],
	['catamarca','andalgalá',''],
	['catamarca','antofagasta',''],
	['catamarca','belén',''],
	['catamarca','capayán',''],
	['catamarca','capital',''],
	['catamarca','4',''],
	['catamarca','corral quemado',''],
	['catamarca','el alto',''],
	['catamarca','el rodeo',''],
	['catamarca','f.mamerto esquiú',''],
	['catamarca','fiambalá',''],
	['catamarca','hualfín',''],
	['catamarca','huillapima',''],
	['catamarca','icaño',''],
	['catamarca','la puerta',''],
	['catamarca','las juntas',''],
	['catamarca','londres',''],
	['catamarca','los altos',''],
	['catamarca','los varela',''],
	['catamarca','mutquín',''],
	['catamarca','paclín',''],
	['catamarca','poman',''],
	['catamarca','pozo de la piedra',''],
	['catamarca','puerta de corral',''],
	['catamarca','puerta san josé',''],
	['catamarca','recreo',''],
	['catamarca','s.f.v de 4',''],
	['catamarca','san fernando',''],
	['catamarca','san fernando del valle',''],
	['catamarca','san josé',''],
	['catamarca','santa maría',''],
	['catamarca','santa rosa',''],
	['catamarca','saujil',''],
	['catamarca','tapso',''],
	['catamarca','tinogasta',''],
	['catamarca','valle viejo',''],
	['catamarca','villa vil',''],
	['chaco','aviá teraí',''],
	['chaco','barranqueras',''],
	['chaco','basail',''],
	['chaco','campo largo',''],
	['chaco','capital',''],
	['chaco','capitán solari',''],
	['chaco','charadai',''],
	['chaco','charata',''],
	['chaco','chorotis',''],
	['chaco','ciervo petiso',''],
	['chaco','cnel. du graty',''],
	['chaco','col. benítez',''],
	['chaco','col. elisa',''],
	['chaco','col. popular',''],
	['chaco','colonias unidas',''],
	['chaco','concepción',''],
	['chaco','corzuela',''],
	['chaco','cote lai',''],
	['chaco','el sauzalito',''],
	['chaco','enrique urien',''],
	['chaco','fontana',''],
	['chaco','fte. esperanza',''],
	['chaco','gancedo',''],
	['chaco','gral. capdevila',''],
	['chaco','gral. pinero',''],
	['chaco','gral. san martín',''],
	['chaco','gral. vedia',''],
	['chaco','hermoso campo',''],
	['chaco','i. del cerrito',''],
	['chaco','j.j. castelli',''],
	['chaco','la clotilde',''],
	['chaco','la eduvigis',''],
	['chaco','la escondida',''],
	['chaco','la leonesa',''],
	['chaco','la tigra',''],
	['chaco','la verde',''],
	['chaco','laguna blanca',''],
	['chaco','laguna limpia',''],
	['chaco','lapachito',''],
	['chaco','las breñas',''],
	['chaco','las garcitas',''],
	['chaco','las palmas',''],
	['chaco','los frentones',''],
	['chaco','machagai',''],
	['chaco','makallé',''],
	['chaco','margarita belén',''],
	['chaco','miraflores',''],
	['chaco','misión n. pompeya',''],
	['chaco','napenay',''],
	['chaco','pampa almirón',''],
	['chaco','pampa del indio',''],
	['chaco','pampa del infierno',''],
	['chaco','pdcia. de la plaza',''],
	['chaco','pdcia. roca',''],
	['chaco','pdcia. roque sáenz peña',''],
	['chaco','pto. bermejo',''],
	['chaco','pto. eva perón',''],
	['chaco','puero tirol',''],
	['chaco','puerto vilelas',''],
	['chaco','quitilipi',''],
	['chaco','resistencia',''],
	['chaco','sáenz peña',''],
	['chaco','samuhú',''],
	['chaco','san bernardo',''],
	['chaco','santa sylvina',''],
	['chaco','taco pozo',''],
	['chaco','tres isletas',''],
	['chaco','villa ángela',''],
	['chaco','villa berthet',''],
	['chaco','villa r. bermejito',''],
	['chubut','aldea apeleg',''],
	['chubut','aldea beleiro',''],
	['chubut','aldea epulef',''],
	['chubut','alto río sengerr',''],
	['chubut','buen pasto',''],
	['chubut','camarones',''],
	['chubut','carrenleufú',''],
	['chubut','cholila',''],
	['chubut','co. centinela',''],
	['chubut','colan conhué',''],
	['chubut','comodoro rivadavia',''],
	['chubut','corcovado',''],
	['chubut','cushamen',''],
	['chubut','dique f. ameghino',''],
	['chubut','dolavón',''],
	['chubut','dr. r. rojas',''],
	['chubut','el hoyo',''],
	['chubut','el maitén',''],
	['chubut','epuyén',''],
	['chubut','esquel',''],
	['chubut','facundo',''],
	['chubut','gaimán',''],
	['chubut','gan gan',''],
	['chubut','gastre',''],
	['chubut','gdor. costa',''],
	['chubut','gualjaina',''],
	['chubut','j. de san martín',''],
	['chubut','lago blanco',''],
	['chubut','lago puelo',''],
	['chubut','lagunita salada',''],
	['chubut','las plumas',''],
	['chubut','los altares',''],
	['chubut','paso de los indios',''],
	['chubut','paso del sapo',''],
	['chubut','pto. madryn',''],
	['chubut','pto. pirámides',''],
	['chubut','rada tilly',''],
	['chubut','rawson',''],
	['chubut','río mayo',''],
	['chubut','río pico',''],
	['chubut','sarmiento',''],
	['chubut','tecka',''],
	['chubut','telsen',''],
	['chubut','trelew',''],
	['chubut','trevelin',''],
	['chubut','veintiocho de julio',''],
	['córdoba','achiras',''],
	['córdoba','adelia maria',''],
	['córdoba','agua de oro',''],
	['córdoba','alcira gigena',''],
	['córdoba','aldea santa maria',''],
	['córdoba','alejandro roca',''],
	['córdoba','alejo ledesma',''],
	['córdoba','alicia',''],
	['córdoba','almafuerte',''],
	['córdoba','alpa corral',''],
	['córdoba','alta gracia',''],
	['córdoba','alto alegre',''],
	['córdoba','alto de los quebrachos',''],
	['córdoba','altos de chipion',''],
	['córdoba','amboy',''],
	['córdoba','ambul',''],
	['córdoba','ana zumaran',''],
	['córdoba','anisacate',''],
	['córdoba','arguello',''],
	['córdoba','arias',''],
	['córdoba','arroyito',''],
	['córdoba','arroyo algodon',''],
	['córdoba','arroyo cabral',''],
	['córdoba','arroyo los patos',''],
	['córdoba','assunta',''],
	['córdoba','atahona',''],
	['córdoba','ausonia',''],
	['córdoba','avellaneda',''],
	['córdoba','ballesteros',''],
	['córdoba','ballesteros sud',''],
	['córdoba','balnearia',''],
	['córdoba','bañado de soto',''],
	['córdoba','bell ville',''],
	['córdoba','bengolea',''],
	['córdoba','benjamin gould',''],
	['córdoba','berrotaran',''],
	['córdoba','bialet masse',''],
	['córdoba','bouwer',''],
	['córdoba','brinkmann',''],
	['córdoba','buchardo',''],
	['córdoba','bulnes',''],
	['córdoba','cabalango',''],
	['córdoba','calamuchita',''],
	['córdoba','calchin',''],
	['córdoba','calchin oeste',''],
	['córdoba','calmayo',''],
	['córdoba','camilo aldao',''],
	['córdoba','caminiaga',''],
	['córdoba','cañada de luque',''],
	['córdoba','cañada de machado',''],
	['córdoba','cañada de rio pinto',''],
	['córdoba','cañada del sauce',''],
	['córdoba','canals',''],
	['córdoba','candelaria sud',''],
	['córdoba','capilla de remedios',''],
	['córdoba','capilla de siton',''],
	['córdoba','capilla del carmen',''],
	['córdoba','capilla del monte',''],
	['córdoba','capital',''],
	['córdoba','capitan gral b. o´higgins',''],
	['córdoba','carnerillo',''],
	['córdoba','carrilobo',''],
	['córdoba','casa grande',''],
	['córdoba','cavanagh',''],
	['córdoba','cerro colorado',''],
	['córdoba','chaján',''],
	['córdoba','chalacea',''],
	['córdoba','chañar viejo',''],
	['córdoba','chancaní',''],
	['córdoba','charbonier',''],
	['córdoba','charras',''],
	['córdoba','chazón',''],
	['córdoba','chilibroste',''],
	['córdoba','chucul',''],
	['córdoba','chuña',''],
	['córdoba','chuña huasi',''],
	['córdoba','churqui cañada',''],
	['córdoba','cienaga del coro',''],
	['córdoba','cintra',''],
	['córdoba','col. almada',''],
	['córdoba','col. anita',''],
	['córdoba','col. barge',''],
	['córdoba','col. bismark',''],
	['córdoba','col. bremen',''],
	['córdoba','col. caroya',''],
	['córdoba','col. italiana',''],
	['córdoba','col. iturraspe',''],
	['córdoba','col. las cuatro esquinas',''],
	['córdoba','col. las pichanas',''],
	['córdoba','col. marina',''],
	['córdoba','col. prosperidad',''],
	['córdoba','col. san bartolome',''],
	['córdoba','col. san pedro',''],
	['córdoba','col. tirolesa',''],
	['córdoba','col. vicente aguero',''],
	['córdoba','col. videla',''],
	['córdoba','col. vignaud',''],
	['córdoba','col. waltelina',''],
	['córdoba','colazo',''],
	['córdoba','comechingones',''],
	['córdoba','conlara',''],
	['córdoba','copacabana',''],
	['córdoba','7',''],
	['córdoba','coronel baigorria',''],
	['córdoba','coronel moldes',''],
	['córdoba','corral de bustos',''],
	['córdoba','corralito',''],
	['córdoba','cosquín',''],
	['córdoba','costa sacate',''],
	['córdoba','cruz alta',''],
	['córdoba','cruz de caña',''],
	['córdoba','cruz del eje',''],
	['córdoba','cuesta blanca',''],
	['córdoba','dean funes',''],
	['córdoba','del campillo',''],
	['córdoba','despeñaderos',''],
	['córdoba','devoto',''],
	['córdoba','diego de rojas',''],
	['córdoba','dique chico',''],
	['córdoba','el arañado',''],
	['córdoba','el brete',''],
	['córdoba','el chacho',''],
	['córdoba','el crispín',''],
	['córdoba','el fortín',''],
	['córdoba','el manzano',''],
	['córdoba','el rastreador',''],
	['córdoba','el rodeo',''],
	['córdoba','el tío',''],
	['córdoba','elena',''],
	['córdoba','embalse',''],
	['córdoba','esquina',''],
	['córdoba','estación gral. paz',''],
	['córdoba','estación juárez celman',''],
	['córdoba','estancia de guadalupe',''],
	['córdoba','estancia vieja',''],
	['córdoba','etruria',''],
	['córdoba','eufrasio loza',''],
	['córdoba','falda del carmen',''],
	['córdoba','freyre',''],
	['córdoba','gral. baldissera',''],
	['córdoba','gral. cabrera',''],
	['córdoba','gral. deheza',''],
	['córdoba','gral. fotheringham',''],
	['córdoba','gral. levalle',''],
	['córdoba','gral. roca',''],
	['córdoba','guanaco muerto',''],
	['córdoba','guasapampa',''],
	['córdoba','guatimozin',''],
	['córdoba','gutenberg',''],
	['córdoba','hernando',''],
	['córdoba','huanchillas',''],
	['córdoba','huerta grande',''],
	['córdoba','huinca renanco',''],
	['córdoba','idiazabal',''],
	['córdoba','impira',''],
	['córdoba','inriville',''],
	['córdoba','isla verde',''],
	['córdoba','italó',''],
	['córdoba','james craik',''],
	['córdoba','jesús maría',''],
	['córdoba','jovita',''],
	['córdoba','justiniano posse',''],
	['córdoba','km 658',''],
	['córdoba','l. v. mansilla',''],
	['córdoba','la batea',''],
	['córdoba','la calera',''],
	['córdoba','la carlota',''],
	['córdoba','la carolina',''],
	['córdoba','la cautiva',''],
	['córdoba','la cesira',''],
	['córdoba','la cruz',''],
	['córdoba','la cumbre',''],
	['córdoba','la cumbrecita',''],
	['córdoba','la falda',''],
	['córdoba','la francia',''],
	['córdoba','la granja',''],
	['córdoba','la higuera',''],
	['córdoba','la laguna',''],
	['córdoba','la paisanita',''],
	['córdoba','la palestina',''],
	['córdoba','12',''],
	['córdoba','la paquita',''],
	['córdoba','la para',''],
	['córdoba','la paz',''],
	['córdoba','la playa',''],
	['córdoba','la playosa',''],
	['córdoba','la población',''],
	['córdoba','la posta',''],
	['córdoba','la puerta',''],
	['córdoba','la quinta',''],
	['córdoba','la rancherita',''],
	['córdoba','la rinconada',''],
	['córdoba','la serranita',''],
	['córdoba','la tordilla',''],
	['córdoba','laborde',''],
	['córdoba','laboulaye',''],
	['córdoba','laguna larga',''],
	['córdoba','las acequias',''],
	['córdoba','las albahacas',''],
	['córdoba','las arrias',''],
	['córdoba','las bajadas',''],
	['córdoba','las caleras',''],
	['córdoba','las calles',''],
	['córdoba','las cañadas',''],
	['córdoba','las gramillas',''],
	['córdoba','las higueras',''],
	['córdoba','las isletillas',''],
	['córdoba','las junturas',''],
	['córdoba','las palmas',''],
	['córdoba','las peñas',''],
	['córdoba','las peñas sud',''],
	['córdoba','las perdices',''],
	['córdoba','las playas',''],
	['córdoba','las rabonas',''],
	['córdoba','las saladas',''],
	['córdoba','las tapias',''],
	['córdoba','las varas',''],
	['córdoba','las varillas',''],
	['córdoba','las vertientes',''],
	['córdoba','leguizamón',''],
	['córdoba','leones',''],
	['córdoba','los cedros',''],
	['córdoba','los cerrillos',''],
	['córdoba','los chañaritos (c.e)',''],
	['córdoba','los chanaritos (r.s)',''],
	['córdoba','los cisnes',''],
	['córdoba','los cocos',''],
	['córdoba','los cóndores',''],
	['córdoba','los hornillos',''],
	['córdoba','los hoyos',''],
	['córdoba','los mistoles',''],
	['córdoba','los molinos',''],
	['córdoba','los pozos',''],
	['córdoba','los reartes',''],
	['córdoba','los surgentes',''],
	['córdoba','los talares',''],
	['córdoba','los zorros',''],
	['córdoba','lozada',''],
	['córdoba','luca',''],
	['córdoba','luque',''],
	['córdoba','luyaba',''],
	['córdoba','malagueño',''],
	['córdoba','malena',''],
	['córdoba','malvinas argentinas',''],
	['córdoba','manfredi',''],
	['córdoba','maquinista gallini',''],
	['córdoba','marcos juárez',''],
	['córdoba','marull',''],
	['córdoba','matorrales',''],
	['córdoba','mattaldi',''],
	['córdoba','mayu sumaj',''],
	['córdoba','media naranja',''],
	['córdoba','melo',''],
	['córdoba','mendiolaza',''],
	['córdoba','mi granja',''],
	['córdoba','mina clavero',''],
	['córdoba','miramar',''],
	['córdoba','morrison',''],
	['córdoba','morteros',''],
	['córdoba','mte. buey',''],
	['córdoba','mte. cristo',''],
	['córdoba','mte. de los gauchos',''],
	['córdoba','mte. leña',''],
	['córdoba','mte. maíz',''],
	['córdoba','mte. ralo',''],
	['córdoba','nicolás bruzone',''],
	['córdoba','noetinger',''],
	['córdoba','nono',''],
	['córdoba','nueva 7',''],
	['córdoba','obispo trejo',''],
	['córdoba','olaeta',''],
	['córdoba','oliva',''],
	['córdoba','olivares san nicolás',''],
	['córdoba','onagolty',''],
	['córdoba','oncativo',''],
	['córdoba','ordoñez',''],
	['córdoba','pacheco de melo',''],
	['córdoba','pampayasta n.',''],
	['córdoba','pampayasta s.',''],
	['córdoba','panaholma',''],
	['córdoba','pascanas',''],
	['córdoba','pasco',''],
	['córdoba','paso del durazno',''],
	['córdoba','paso viejo',''],
	['córdoba','pilar',''],
	['córdoba','pincén',''],
	['córdoba','piquillín',''],
	['córdoba','plaza de mercedes',''],
	['córdoba','plaza luxardo',''],
	['córdoba','porteña',''],
	['córdoba','potrero de garay',''],
	['córdoba','pozo del molle',''],
	['córdoba','pozo nuevo',''],
	['córdoba','pueblo italiano',''],
	['córdoba','puesto de castro',''],
	['córdoba','punta del agua',''],
	['córdoba','quebracho herrado',''],
	['córdoba','quilino',''],
	['córdoba','rafael garcía',''],
	['córdoba','ranqueles',''],
	['córdoba','rayo cortado',''],
	['córdoba','reducción',''],
	['córdoba','rincón',''],
	['córdoba','río bamba',''],
	['córdoba','río ceballos',''],
	['córdoba','río cuarto',''],
	['córdoba','río de los sauces',''],
	['córdoba','río primero',''],
	['córdoba','río segundo',''],
	['córdoba','río tercero',''],
	['córdoba','rosales',''],
	['córdoba','rosario del saladillo',''],
	['córdoba','sacanta',''],
	['córdoba','sagrada familia',''],
	['córdoba','saira',''],
	['córdoba','saladillo',''],
	['córdoba','saldán',''],
	['córdoba','salsacate',''],
	['córdoba','salsipuedes',''],
	['córdoba','sampacho',''],
	['córdoba','san agustín',''],
	['córdoba','san antonio de arredondo',''],
	['córdoba','san antonio de litín',''],
	['córdoba','san basilio',''],
	['córdoba','san carlos minas',''],
	['córdoba','san clemente',''],
	['córdoba','san esteban',''],
	['córdoba','san francisco',''],
	['córdoba','san ignacio',''],
	['córdoba','san javier',''],
	['córdoba','san jerónimo',''],
	['córdoba','san joaquín',''],
	['córdoba','san josé de la dormida',''],
	['córdoba','san josé de las salinas',''],
	['córdoba','san lorenzo',''],
	['córdoba','san marcos sierras',''],
	['córdoba','san marcos sud',''],
	['córdoba','san pedro',''],
	['córdoba','san pedro n.',''],
	['córdoba','san roque',''],
	['córdoba','san vicente',''],
	['córdoba','santa catalina',''],
	['córdoba','santa elena',''],
	['córdoba','santa eufemia',''],
	['córdoba','santa maria',''],
	['córdoba','sarmiento',''],
	['córdoba','saturnino m.laspiur',''],
	['córdoba','sauce arriba',''],
	['córdoba','sebastián elcano',''],
	['córdoba','seeber',''],
	['córdoba','segunda usina',''],
	['córdoba','serrano',''],
	['córdoba','serrezuela',''],
	['córdoba','sgo. temple',''],
	['córdoba','silvio pellico',''],
	['córdoba','simbolar',''],
	['córdoba','sinsacate',''],
	['córdoba','sta. rosa de calamuchita',''],
	['córdoba','sta. rosa de río primero',''],
	['córdoba','suco',''],
	['córdoba','tala cañada',''],
	['córdoba','tala huasi',''],
	['córdoba','talaini',''],
	['córdoba','tancacha',''],
	['córdoba','tanti',''],
	['córdoba','ticino',''],
	['córdoba','tinoco',''],
	['córdoba','tío pujio',''],
	['córdoba','toledo',''],
	['córdoba','toro pujio',''],
	['córdoba','tosno',''],
	['córdoba','tosquita',''],
	['córdoba','tránsito',''],
	['córdoba','tuclame',''],
	['córdoba','tutti',''],
	['córdoba','ucacha',''],
	['córdoba','unquillo',''],
	['córdoba','valle de anisacate',''],
	['córdoba','valle hermoso',''],
	['córdoba','vélez sarfield',''],
	['córdoba','viamonte',''],
	['córdoba','vicuña mackenna',''],
	['córdoba','villa allende',''],
	['córdoba','villa amancay',''],
	['córdoba','villa ascasubi',''],
	['córdoba','villa candelaria n.',''],
	['córdoba','villa carlos paz',''],
	['córdoba','villa cerro azul',''],
	['córdoba','villa ciudad de américa',''],
	['córdoba','villa ciudad pque los reartes',''],
	['córdoba','villa concepción del tío',''],
	['córdoba','villa cura brochero',''],
	['córdoba','villa de las rosas',''],
	['córdoba','villa de maría',''],
	['córdoba','villa de pocho',''],
	['córdoba','villa de soto',''],
	['córdoba','villa del dique',''],
	['córdoba','villa del prado',''],
	['córdoba','villa del rosario',''],
	['córdoba','villa del totoral',''],
	['córdoba','villa dolores',''],
	['córdoba','villa el chancay',''],
	['córdoba','villa elisa',''],
	['córdoba','villa flor serrana',''],
	['córdoba','villa fontana',''],
	['córdoba','villa giardino',''],
	['córdoba','villa gral. belgrano',''],
	['córdoba','villa gutierrez',''],
	['córdoba','villa huidobro',''],
	['córdoba','villa la bolsa',''],
	['córdoba','villa los aromos',''],
	['córdoba','villa los patos',''],
	['córdoba','villa maría',''],
	['córdoba','villa nueva',''],
	['córdoba','villa pque. santa ana',''],
	['córdoba','villa pque. siquiman',''],
	['córdoba','villa quillinzo',''],
	['córdoba','villa rossi',''],
	['córdoba','villa rumipal',''],
	['córdoba','villa san esteban',''],
	['córdoba','villa san isidro',''],
	['córdoba','villa 21',''],
	['córdoba','villa sarmiento (g.r)',''],
	['córdoba','villa sarmiento (s.a)',''],
	['córdoba','villa tulumba',''],
	['córdoba','villa valeria',''],
	['córdoba','villa yacanto',''],
	['córdoba','washington',''],
	['córdoba','wenceslao escalante',''],
	['córdoba','ycho cruz sierras',''],
	['corrientes','alvear',''],
	['corrientes','bella vista',''],
	['corrientes','berón de astrada',''],
	['corrientes','bonpland',''],
	['corrientes','caá cati',''],
	['corrientes','capital',''],
	['corrientes','chavarría',''],
	['corrientes','col. c. pellegrini',''],
	['corrientes','col. libertad',''],
	['corrientes','col. liebig',''],
	['corrientes','col. sta rosa',''],
	['corrientes','concepción',''],
	['corrientes','cruz de los milagros',''],
	['corrientes','curuzú-cuatiá',''],
	['corrientes','empedrado',''],
	['corrientes','esquina',''],
	['corrientes','estación torrent',''],
	['corrientes','felipe yofré',''],
	['corrientes','garruchos',''],
	['corrientes','gdor. agrónomo',''],
	['corrientes','gdor. martínez',''],
	['corrientes','goya',''],
	['corrientes','guaviravi',''],
	['corrientes','herlitzka',''],
	['corrientes','ita-ibate',''],
	['corrientes','itatí',''],
	['corrientes','ituzaingó',''],
	['corrientes','josé rafael gómez',''],
	['corrientes','juan pujol',''],
	['corrientes','la cruz',''],
	['corrientes','lavalle',''],
	['corrientes','lomas de vallejos',''],
	['corrientes','loreto',''],
	['corrientes','mariano i. loza',''],
	['corrientes','mburucuyá',''],
	['corrientes','mercedes',''],
	['corrientes','mocoretá',''],
	['corrientes','mte. caseros',''],
	['corrientes','nueve de julio',''],
	['corrientes','palmar grande',''],
	['corrientes','parada pucheta',''],
	['corrientes','paso de la patria',''],
	['corrientes','paso de los libres',''],
	['corrientes','pedro r. fernandez',''],
	['corrientes','perugorría',''],
	['corrientes','pueblo libertador',''],
	['corrientes','ramada paso',''],
	['corrientes','riachuelo',''],
	['corrientes','saladas',''],
	['corrientes','san antonio',''],
	['corrientes','san carlos',''],
	['corrientes','san cosme',''],
	['corrientes','san lorenzo',''],
	['corrientes','20 del palmar',''],
	['corrientes','san miguel',''],
	['corrientes','san roque',''],
	['corrientes','santa ana',''],
	['corrientes','santa lucía',''],
	['corrientes','santo tomé',''],
	['corrientes','sauce',''],
	['corrientes','tabay',''],
	['corrientes','tapebicuá',''],
	['corrientes','tatacua',''],
	['corrientes','virasoro',''],
	['corrientes','yapeyú',''],
	['corrientes','yataití calle',''],
	['entre ríos','alarcón',''],
	['entre ríos','alcaraz',''],
	['entre ríos','alcaraz n.',''],
	['entre ríos','alcaraz s.',''],
	['entre ríos','aldea asunción',''],
	['entre ríos','aldea brasilera',''],
	['entre ríos','aldea elgenfeld',''],
	['entre ríos','aldea grapschental',''],
	['entre ríos','aldea ma. luisa',''],
	['entre ríos','aldea protestante',''],
	['entre ríos','aldea salto',''],
	['entre ríos','aldea san antonio (g)',''],
	['entre ríos','aldea san antonio (p)',''],
	['entre ríos','aldea 19',''],
	['entre ríos','aldea san miguel',''],
	['entre ríos','aldea san rafael',''],
	['entre ríos','aldea spatzenkutter',''],
	['entre ríos','aldea sta. maría',''],
	['entre ríos','aldea sta. rosa',''],
	['entre ríos','aldea valle maría',''],
	['entre ríos','altamirano sur',''],
	['entre ríos','antelo',''],
	['entre ríos','antonio tomás',''],
	['entre ríos','aranguren',''],
	['entre ríos','arroyo barú',''],
	['entre ríos','arroyo burgos',''],
	['entre ríos','arroyo clé',''],
	['entre ríos','arroyo corralito',''],
	['entre ríos','arroyo del medio',''],
	['entre ríos','arroyo maturrango',''],
	['entre ríos','arroyo palo seco',''],
	['entre ríos','banderas',''],
	['entre ríos','basavilbaso',''],
	['entre ríos','betbeder',''],
	['entre ríos','bovril',''],
	['entre ríos','caseros',''],
	['entre ríos','ceibas',''],
	['entre ríos','cerrito',''],
	['entre ríos','chajarí',''],
	['entre ríos','chilcas',''],
	['entre ríos','clodomiro ledesma',''],
	['entre ríos','col. alemana',''],
	['entre ríos','col. avellaneda',''],
	['entre ríos','col. avigdor',''],
	['entre ríos','col. ayuí',''],
	['entre ríos','col. baylina',''],
	['entre ríos','col. carrasco',''],
	['entre ríos','col. celina',''],
	['entre ríos','col. cerrito',''],
	['entre ríos','col. crespo',''],
	['entre ríos','col. elia',''],
	['entre ríos','col. ensayo',''],
	['entre ríos','col. gral. roca',''],
	['entre ríos','col. la argentina',''],
	['entre ríos','col. merou',''],
	['entre ríos','col. oficial nª3',''],
	['entre ríos','col. oficial nº13',''],
	['entre ríos','col. oficial nº14',''],
	['entre ríos','col. oficial nº5',''],
	['entre ríos','col. reffino',''],
	['entre ríos','col. tunas',''],
	['entre ríos','col. viraró',''],
	['entre ríos','colón',''],
	['entre ríos','concepción del uruguay',''],
	['entre ríos','concordia',''],
	['entre ríos','conscripto bernardi',''],
	['entre ríos','costa grande',''],
	['entre ríos','costa san antonio',''],
	['entre ríos','costa uruguay n.',''],
	['entre ríos','costa uruguay s.',''],
	['entre ríos','crespo',''],
	['entre ríos','crucecitas 3ª',''],
	['entre ríos','crucecitas 7ª',''],
	['entre ríos','crucecitas 8ª',''],
	['entre ríos','cuchilla redonda',''],
	['entre ríos','curtiembre',''],
	['entre ríos','diamante',''],
	['entre ríos','distrito 6º',''],
	['entre ríos','distrito chañar',''],
	['entre ríos','distrito chiqueros',''],
	['entre ríos','distrito cuarto',''],
	['entre ríos','distrito diego lópez',''],
	['entre ríos','distrito pajonal',''],
	['entre ríos','distrito sauce',''],
	['entre ríos','distrito tala',''],
	['entre ríos','distrito talitas',''],
	['entre ríos','don cristóbal 1ª sección',''],
	['entre ríos','don cristóbal 2ª sección',''],
	['entre ríos','durazno',''],
	['entre ríos','el cimarrón',''],
	['entre ríos','el gramillal',''],
	['entre ríos','el palenque',''],
	['entre ríos','el pingo',''],
	['entre ríos','el quebracho',''],
	['entre ríos','el redomón',''],
	['entre ríos','el solar',''],
	['entre ríos','enrique carbo',''],
	['entre ríos','9',''],
	['entre ríos','espinillo n.',''],
	['entre ríos','estación campos',''],
	['entre ríos','estación escriña',''],
	['entre ríos','estación lazo',''],
	['entre ríos','estación raíces',''],
	['entre ríos','estación yerúa',''],
	['entre ríos','estancia grande',''],
	['entre ríos','estancia líbaros',''],
	['entre ríos','estancia racedo',''],
	['entre ríos','estancia solá',''],
	['entre ríos','estancia yuquerí',''],
	['entre ríos','estaquitas',''],
	['entre ríos','faustino m. parera',''],
	['entre ríos','febre',''],
	['entre ríos','federación',''],
	['entre ríos','federal',''],
	['entre ríos','gdor. echagüe',''],
	['entre ríos','gdor. mansilla',''],
	['entre ríos','gilbert',''],
	['entre ríos','gonzález calderón',''],
	['entre ríos','gral. almada',''],
	['entre ríos','gral. alvear',''],
	['entre ríos','gral. campos',''],
	['entre ríos','gral. galarza',''],
	['entre ríos','gral. ramírez',''],
	['entre ríos','gualeguay',''],
	['entre ríos','gualeguaychú',''],
	['entre ríos','gualeguaycito',''],
	['entre ríos','guardamonte',''],
	['entre ríos','hambis',''],
	['entre ríos','hasenkamp',''],
	['entre ríos','hernandarias',''],
	['entre ríos','hernández',''],
	['entre ríos','herrera',''],
	['entre ríos','hinojal',''],
	['entre ríos','hocker',''],
	['entre ríos','ing. sajaroff',''],
	['entre ríos','irazusta',''],
	['entre ríos','isletas',''],
	['entre ríos','j.j de urquiza',''],
	['entre ríos','jubileo',''],
	['entre ríos','la clarita',''],
	['entre ríos','la criolla',''],
	['entre ríos','la esmeralda',''],
	['entre ríos','la florida',''],
	['entre ríos','la fraternidad',''],
	['entre ríos','la hierra',''],
	['entre ríos','la ollita',''],
	['entre ríos','la paz',''],
	['entre ríos','la picada',''],
	['entre ríos','la providencia',''],
	['entre ríos','la verbena',''],
	['entre ríos','laguna benítez',''],
	['entre ríos','larroque',''],
	['entre ríos','las cuevas',''],
	['entre ríos','las garzas',''],
	['entre ríos','las guachas',''],
	['entre ríos','las mercedes',''],
	['entre ríos','las moscas',''],
	['entre ríos','las mulitas',''],
	['entre ríos','las toscas',''],
	['entre ríos','laurencena',''],
	['entre ríos','libertador san martín',''],
	['entre ríos','loma limpia',''],
	['entre ríos','los ceibos',''],
	['entre ríos','los charruas',''],
	['entre ríos','los conquistadores',''],
	['entre ríos','lucas gonzález',''],
	['entre ríos','lucas n.',''],
	['entre ríos','lucas s. 1ª',''],
	['entre ríos','lucas s. 2ª',''],
	['entre ríos','maciá',''],
	['entre ríos','maría grande',''],
	['entre ríos','maría grande 2ª',''],
	['entre ríos','médanos',''],
	['entre ríos','mojones n.',''],
	['entre ríos','mojones s.',''],
	['entre ríos','molino doll',''],
	['entre ríos','monte redondo',''],
	['entre ríos','montoya',''],
	['entre ríos','mulas grandes',''],
	['entre ríos','ñancay',''],
	['entre ríos','nogoyá',''],
	['entre ríos','nueva escocia',''],
	['entre ríos','nueva vizcaya',''],
	['entre ríos','ombú',''],
	['entre ríos','oro verde',''],
	['entre ríos','paraná',''],
	['entre ríos','pasaje guayaquil',''],
	['entre ríos','pasaje las tunas',''],
	['entre ríos','paso de la arena',''],
	['entre ríos','paso de la laguna',''],
	['entre ríos','paso de las piedras',''],
	['entre ríos','paso duarte',''],
	['entre ríos','pastor britos',''],
	['entre ríos','pedernal',''],
	['entre ríos','perdices',''],
	['entre ríos','picada berón',''],
	['entre ríos','piedras blancas',''],
	['entre ríos','primer distrito cuchilla',''],
	['entre ríos','primero de mayo',''],
	['entre ríos','pronunciamiento',''],
	['entre ríos','pto. algarrobo',''],
	['entre ríos','pto. ibicuy',''],
	['entre ríos','pueblo brugo',''],
	['entre ríos','pueblo cazes',''],
	['entre ríos','pueblo gral. belgrano',''],
	['entre ríos','pueblo liebig',''],
	['entre ríos','puerto yeruá',''],
	['entre ríos','punta del monte',''],
	['entre ríos','quebracho',''],
	['entre ríos','quinto distrito',''],
	['entre ríos','raices oeste',''],
	['entre ríos','rincón de nogoyá',''],
	['entre ríos','rincón del cinto',''],
	['entre ríos','rincón del doll',''],
	['entre ríos','rincón del gato',''],
	['entre ríos','rocamora',''],
	['entre ríos','rosario del tala',''],
	['entre ríos','san benito',''],
	['entre ríos','san cipriano',''],
	['entre ríos','san ernesto',''],
	['entre ríos','san gustavo',''],
	['entre ríos','san jaime',''],
	['entre ríos','san josé',''],
	['entre ríos','san josé de feliciano',''],
	['entre ríos','san justo',''],
	['entre ríos','san marcial',''],
	['entre ríos','san pedro',''],
	['entre ríos','san ramírez',''],
	['entre ríos','san ramón',''],
	['entre ríos','san roque',''],
	['entre ríos','san salvador',''],
	['entre ríos','san víctor',''],
	['entre ríos','santa ana',''],
	['entre ríos','santa anita',''],
	['entre ríos','santa elena',''],
	['entre ríos','santa lucía',''],
	['entre ríos','santa luisa',''],
	['entre ríos','sauce de luna',''],
	['entre ríos','sauce montrull',''],
	['entre ríos','sauce pinto',''],
	['entre ríos','sauce sur',''],
	['entre ríos','seguí',''],
	['entre ríos','sir leonard',''],
	['entre ríos','sosa',''],
	['entre ríos','tabossi',''],
	['entre ríos','tezanos pinto',''],
	['entre ríos','ubajay',''],
	['entre ríos','urdinarrain',''],
	['entre ríos','veinte de septiembre',''],
	['entre ríos','viale',''],
	['entre ríos','victoria',''],
	['entre ríos','villa clara',''],
	['entre ríos','villa del rosario',''],
	['entre ríos','villa domínguez',''],
	['entre ríos','villa elisa',''],
	['entre ríos','villa fontana',''],
	['entre ríos','villa gdor. etchevehere',''],
	['entre ríos','villa mantero',''],
	['entre ríos','villa paranacito',''],
	['entre ríos','villa urquiza',''],
	['entre ríos','villaguay',''],
	['entre ríos','walter moss',''],
	['entre ríos','yacaré',''],
	['entre ríos','yeso oeste',''],
	['formosa','buena vista',''],
	['formosa','clorinda',''],
	['formosa','col. pastoril',''],
	['formosa','cte. fontana',''],
	['formosa','el colorado',''],
	['formosa','el espinillo',''],
	['formosa','estanislao del campo',''],
	['formosa','10',''],
	['formosa','fortín lugones',''],
	['formosa','gral. lucio v. mansilla',''],
	['formosa','gral. manuel belgrano',''],
	['formosa','gral. mosconi',''],
	['formosa','gran guardia',''],
	['formosa','herradura',''],
	['formosa','ibarreta',''],
	['formosa','ing. juárez',''],
	['formosa','laguna blanca',''],
	['formosa','laguna naick neck',''],
	['formosa','laguna yema',''],
	['formosa','las lomitas',''],
	['formosa','los chiriguanos',''],
	['formosa','mayor v. villafañe',''],
	['formosa','misión san fco.',''],
	['formosa','palo santo',''],
	['formosa','pirané',''],
	['formosa','pozo del maza',''],
	['formosa','riacho he-he',''],
	['formosa','san hilario',''],
	['formosa','san martín ii',''],
	['formosa','siete palmas',''],
	['formosa','subteniente perín',''],
	['formosa','tres lagunas',''],
	['formosa','villa dos trece',''],
	['formosa','villa escolar',''],
	['formosa','villa gral. güemes',''],
	['jujuy','abdon castro tolay',''],
	['jujuy','abra pampa',''],
	['jujuy','abralaite',''],
	['jujuy','aguas calientes',''],
	['jujuy','arrayanal',''],
	['jujuy','barrios',''],
	['jujuy','caimancito',''],
	['jujuy','calilegua',''],
	['jujuy','cangrejillos',''],
	['jujuy','caspala',''],
	['jujuy','catuá',''],
	['jujuy','cieneguillas',''],
	['jujuy','coranzulli',''],
	['jujuy','cusi-cusi',''],
	['jujuy','el aguilar',''],
	['jujuy','el carmen',''],
	['jujuy','el cóndor',''],
	['jujuy','el fuerte',''],
	['jujuy','el piquete',''],
	['jujuy','el talar',''],
	['jujuy','fraile pintado',''],
	['jujuy','hipólito yrigoyen',''],
	['jujuy','huacalera',''],
	['jujuy','humahuaca',''],
	['jujuy','la esperanza',''],
	['jujuy','la mendieta',''],
	['jujuy','la quiaca',''],
	['jujuy','ledesma',''],
	['jujuy','libertador gral. san martin',''],
	['jujuy','maimara',''],
	['jujuy','mina pirquitas',''],
	['jujuy','monterrico',''],
	['jujuy','palma sola',''],
	['jujuy','palpalá',''],
	['jujuy','pampa blanca',''],
	['jujuy','pampichuela',''],
	['jujuy','perico',''],
	['jujuy','puesto del marqués',''],
	['jujuy','puesto viejo',''],
	['jujuy','pumahuasi',''],
	['jujuy','purmamarca',''],
	['jujuy','rinconada',''],
	['jujuy','rodeitos',''],
	['jujuy','rosario de río grande',''],
	['jujuy','san antonio',''],
	['jujuy','san francisco',''],
	['jujuy','san pedro',''],
	['jujuy','san rafael',''],
	['jujuy','san salvador',''],
	['jujuy','santa ana',''],
	['jujuy','santa catalina',''],
	['jujuy','santa clara',''],
	['jujuy','susques',''],
	['jujuy','tilcara',''],
	['jujuy','tres cruces',''],
	['jujuy','tumbaya',''],
	['jujuy','valle grande',''],
	['jujuy','vinalito',''],
	['jujuy','volcán',''],
	['jujuy','yala',''],
	['jujuy','yaví',''],
	['jujuy','yuto',''],
	['la pampa','abramo',''],
	['la pampa','adolfo van praet',''],
	['la pampa','agustoni',''],
	['la pampa','algarrobo del aguila',''],
	['la pampa','alpachiri',''],
	['la pampa','alta italia',''],
	['la pampa','anguil',''],
	['la pampa','arata',''],
	['la pampa','ataliva roca',''],
	['la pampa','bernardo larroude',''],
	['la pampa','bernasconi',''],
	['la pampa','caleufú',''],
	['la pampa','carro quemado',''],
	['la pampa','catriló',''],
	['la pampa','ceballos',''],
	['la pampa','chacharramendi',''],
	['la pampa','col. barón',''],
	['la pampa','col. santa maría',''],
	['la pampa','conhelo',''],
	['la pampa','coronel hilario lagos',''],
	['la pampa','cuchillo-có',''],
	['la pampa','doblas',''],
	['la pampa','dorila',''],
	['la pampa','eduardo castex',''],
	['la pampa','embajador martini',''],
	['la pampa','falucho',''],
	['la pampa','gral. acha',''],
	['la pampa','gral. manuel campos',''],
	['la pampa','gral. pico',''],
	['la pampa','guatraché',''],
	['la pampa','ing. luiggi',''],
	['la pampa','intendente alvear',''],
	['la pampa','jacinto arauz',''],
	['la pampa','la adela',''],
	['la pampa','la humada',''],
	['la pampa','la maruja',''],
	['la pampa','12',''],
	['la pampa','la reforma',''],
	['la pampa','limay mahuida',''],
	['la pampa','lonquimay',''],
	['la pampa','loventuel',''],
	['la pampa','luan toro',''],
	['la pampa','macachín',''],
	['la pampa','maisonnave',''],
	['la pampa','mauricio mayer',''],
	['la pampa','metileo',''],
	['la pampa','miguel cané',''],
	['la pampa','miguel riglos',''],
	['la pampa','monte nievas',''],
	['la pampa','parera',''],
	['la pampa','perú',''],
	['la pampa','pichi-huinca',''],
	['la pampa','puelches',''],
	['la pampa','puelén',''],
	['la pampa','quehue',''],
	['la pampa','quemú quemú',''],
	['la pampa','quetrequén',''],
	['la pampa','rancul',''],
	['la pampa','realicó',''],
	['la pampa','relmo',''],
	['la pampa','rolón',''],
	['la pampa','rucanelo',''],
	['la pampa','sarah',''],
	['la pampa','speluzzi',''],
	['la pampa','sta. isabel',''],
	['la pampa','sta. rosa',''],
	['la pampa','sta. teresa',''],
	['la pampa','telén',''],
	['la pampa','toay',''],
	['la pampa','tomas m. de anchorena',''],
	['la pampa','trenel',''],
	['la pampa','unanue',''],
	['la pampa','uriburu',''],
	['la pampa','veinticinco de mayo',''],
	['la pampa','vertiz',''],
	['la pampa','victorica',''],
	['la pampa','villa mirasol',''],
	['la pampa','winifreda',''],
	['la rioja','arauco',''],
	['la rioja','capital',''],
	['la rioja','castro barros',''],
	['la rioja','chamical',''],
	['la rioja','chilecito',''],
	['la rioja','coronel f. varela',''],
	['la rioja','famatina',''],
	['la rioja','gral. a.v.peñaloza',''],
	['la rioja','gral. belgrano',''],
	['la rioja','gral. j.f. quiroga',''],
	['la rioja','gral. lamadrid',''],
	['la rioja','gral. ocampo',''],
	['la rioja','gral. san martín',''],
	['la rioja','independencia',''],
	['la rioja','rosario penaloza',''],
	['la rioja','san blas de los sauces',''],
	['la rioja','sanagasta',''],
	['la rioja','vinchina',''],
	['mendoza','capital',''],
	['mendoza','chacras de coria',''],
	['mendoza','dorrego',''],
	['mendoza','gllen',''],
	['mendoza','godoy cruz',''],
	['mendoza','gral. alvear',''],
	['mendoza','guaymallén',''],
	['mendoza','junín',''],
	['mendoza','la paz',''],
	['mendoza','las heras',''],
	['mendoza','lavalle',''],
	['mendoza','luján',''],
	['mendoza','luján de cuyo',''],
	['mendoza','maipú',''],
	['mendoza','malargüe',''],
	['mendoza','rivadavia',''],
	['mendoza','san carlos',''],
	['mendoza','san martín',''],
	['mendoza','san rafael',''],
	['mendoza','sta. rosa',''],
	['mendoza','tunuyán',''],
	['mendoza','tupungato',''],
	['mendoza','villa nueva',''],
	['misiones','alba posse',''],
	['misiones','almafuerte',''],
	['misiones','apóstoles',''],
	['misiones','aristóbulo del valle',''],
	['misiones','arroyo del medio',''],
	['misiones','azara',''],
	['misiones','bdo. de irigoyen',''],
	['misiones','bonpland',''],
	['misiones','caá yari',''],
	['misiones','campo grande',''],
	['misiones','campo ramón',''],
	['misiones','campo viera',''],
	['misiones','candelaria',''],
	['misiones','capioví',''],
	['misiones','caraguatay',''],
	['misiones','cdte. guacurarí',''],
	['misiones','cerro azul',''],
	['misiones','cerro corá',''],
	['misiones','col. alberdi',''],
	['misiones','col. aurora',''],
	['misiones','col. delicia',''],
	['misiones','col. polana',''],
	['misiones','col. victoria',''],
	['misiones','col. wanda',''],
	['misiones','concepción de la sierra',''],
	['misiones','corpus',''],
	['misiones','dos arroyos',''],
	['misiones','dos de mayo',''],
	['misiones','el alcázar',''],
	['misiones','el dorado',''],
	['misiones','el soberbio',''],
	['misiones','esperanza',''],
	['misiones','f. ameghino',''],
	['misiones','fachinal',''],
	['misiones','garuhapé',''],
	['misiones','garupá',''],
	['misiones','gdor. lópez',''],
	['misiones','gdor. roca',''],
	['misiones','gral. alvear',''],
	['misiones','gral. urquiza',''],
	['misiones','guaraní',''],
	['misiones','h. yrigoyen',''],
	['misiones','iguazú',''],
	['misiones','itacaruaré',''],
	['misiones','jardín américa',''],
	['misiones','leandro n. alem',''],
	['misiones','libertad',''],
	['misiones','loreto',''],
	['misiones','los helechos',''],
	['misiones','mártires',''],
	['misiones','15',''],
	['misiones','mojón grande',''],
	['misiones','montecarlo',''],
	['misiones','nueve de julio',''],
	['misiones','oberá',''],
	['misiones','olegario v. andrade',''],
	['misiones','panambí',''],
	['misiones','posadas',''],
	['misiones','profundidad',''],
	['misiones','pto. iguazú',''],
	['misiones','pto. leoni',''],
	['misiones','pto. piray',''],
	['misiones','pto. rico',''],
	['misiones','ruiz de montoya',''],
	['misiones','san antonio',''],
	['misiones','san ignacio',''],
	['misiones','san javier',''],
	['misiones','san josé',''],
	['misiones','san martín',''],
	['misiones','san pedro',''],
	['misiones','san vicente',''],
	['misiones','santiago de liniers',''],
	['misiones','santo pipo',''],
	['misiones','sta. ana',''],
	['misiones','sta. maría',''],
	['misiones','tres capones',''],
	['misiones','veinticinco de mayo',''],
	['misiones','wanda',''],
	['neuquén','aguada san roque',''],
	['neuquén','aluminé',''],
	['neuquén','andacollo',''],
	['neuquén','añelo',''],
	['neuquén','bajada del agrio',''],
	['neuquén','barrancas',''],
	['neuquén','buta ranquil',''],
	['neuquén','capital',''],
	['neuquén','caviahué',''],
	['neuquén','centenario',''],
	['neuquén','chorriaca',''],
	['neuquén','chos malal',''],
	['neuquén','cipolletti',''],
	['neuquén','covunco abajo',''],
	['neuquén','coyuco cochico',''],
	['neuquén','cutral có',''],
	['neuquén','el cholar',''],
	['neuquén','el huecú',''],
	['neuquén','el sauce',''],
	['neuquén','guañacos',''],
	['neuquén','huinganco',''],
	['neuquén','las coloradas',''],
	['neuquén','las lajas',''],
	['neuquén','las ovejas',''],
	['neuquén','loncopué',''],
	['neuquén','los catutos',''],
	['neuquén','los chihuidos',''],
	['neuquén','los miches',''],
	['neuquén','manzano amargo',''],
	['neuquén','16',''],
	['neuquén','octavio pico',''],
	['neuquén','paso aguerre',''],
	['neuquén','picún leufú',''],
	['neuquén','piedra del aguila',''],
	['neuquén','pilo lil',''],
	['neuquén','plaza huincul',''],
	['neuquén','plottier',''],
	['neuquén','quili malal',''],
	['neuquén','ramón castro',''],
	['neuquén','rincón de los sauces',''],
	['neuquén','san martín de los andes',''],
	['neuquén','san patricio del chañar',''],
	['neuquén','santo tomás',''],
	['neuquén','sauzal bonito',''],
	['neuquén','senillosa',''],
	['neuquén','taquimilán',''],
	['neuquén','tricao malal',''],
	['neuquén','varvarco',''],
	['neuquén','villa curí leuvu',''],
	['neuquén','villa del nahueve',''],
	['neuquén','villa del puente picún leuvú',''],
	['neuquén','villa el chocón',''],
	['neuquén','villa la angostura',''],
	['neuquén','villa pehuenia',''],
	['neuquén','villa traful',''],
	['neuquén','vista alegre',''],
	['neuquén','zapala',''],
	['río negro','aguada cecilio',''],
	['río negro','aguada de guerra',''],
	['río negro','allén',''],
	['río negro','arroyo de la ventana',''],
	['río negro','arroyo los berros',''],
	['río negro','bariloche',''],
	['río negro','calte. cordero',''],
	['río negro','campo grande',''],
	['río negro','catriel',''],
	['río negro','cerro policía',''],
	['río negro','cervantes',''],
	['río negro','chelforo',''],
	['río negro','chimpay',''],
	['río negro','chinchinales',''],
	['río negro','chipauquil',''],
	['río negro','choele choel',''],
	['río negro','cinco saltos',''],
	['río negro','cipolletti',''],
	['río negro','clemente onelli',''],
	['río negro','colán conhue',''],
	['río negro','comallo',''],
	['río negro','comicó',''],
	['río negro','cona niyeu',''],
	['río negro','coronel belisle',''],
	['río negro','cubanea',''],
	['río negro','darwin',''],
	['río negro','dina huapi',''],
	['río negro','el bolsón',''],
	['río negro','el caín',''],
	['río negro','el manso',''],
	['río negro','gral. conesa',''],
	['río negro','gral. enrique godoy',''],
	['río negro','gral. fernandez oro',''],
	['río negro','gral. roca',''],
	['río negro','guardia mitre',''],
	['río negro','ing. huergo',''],
	['río negro','ing. jacobacci',''],
	['río negro','laguna blanca',''],
	['río negro','lamarque',''],
	['río negro','las grutas',''],
	['río negro','los menucos',''],
	['río negro','luis beltrán',''],
	['río negro','mainqué',''],
	['río negro','mamuel choique',''],
	['río negro','maquinchao',''],
	['río negro','mencué',''],
	['río negro','mtro. ramos mexia',''],
	['río negro','nahuel niyeu',''],
	['río negro','naupa huen',''],
	['río negro','ñorquinco',''],
	['río negro','ojos de agua',''],
	['río negro','paso de agua',''],
	['río negro','paso flores',''],
	['río negro','peñas blancas',''],
	['río negro','pichi mahuida',''],
	['río negro','pilcaniyeu',''],
	['río negro','pomona',''],
	['río negro','prahuaniyeu',''],
	['río negro','rincón treneta',''],
	['río negro','río chico',''],
	['río negro','río colorado',''],
	['río negro','roca',''],
	['río negro','san antonio oeste',''],
	['río negro','san javier',''],
	['río negro','sierra colorada',''],
	['río negro','sierra grande',''],
	['río negro','sierra pailemán',''],
	['río negro','valcheta',''],
	['río negro','valle azul',''],
	['río negro','viedma',''],
	['río negro','villa llanquín',''],
	['río negro','villa mascardi',''],
	['río negro','villa regina',''],
	['río negro','yaminué',''],
	['salta','a. saravia',''],
	['salta','aguaray',''],
	['salta','angastaco',''],
	['salta','animaná',''],
	['salta','cachi',''],
	['salta','cafayate',''],
	['salta','campo quijano',''],
	['salta','campo santo',''],
	['salta','capital',''],
	['salta','cerrillos',''],
	['salta','chicoana',''],
	['salta','col. sta. rosa',''],
	['salta','coronel moldes',''],
	['salta','el bordo',''],
	['salta','el carril',''],
	['salta','el galpón',''],
	['salta','el jardín',''],
	['salta','el potrero',''],
	['salta','el quebrachal',''],
	['salta','el tala',''],
	['salta','embarcación',''],
	['salta','gral. ballivian',''],
	['salta','gral. güemes',''],
	['salta','gral. mosconi',''],
	['salta','gral. pizarro',''],
	['salta','guachipas',''],
	['salta','hipólito yrigoyen',''],
	['salta','iruyá',''],
	['salta','isla de cañas',''],
	['salta','j. v. gonzalez',''],
	['salta','la caldera',''],
	['salta','la candelaria',''],
	['salta','la merced',''],
	['salta','la poma',''],
	['salta','la viña',''],
	['salta','las lajitas',''],
	['salta','los toldos',''],
	['salta','metán',''],
	['salta','molinos',''],
	['salta','nazareno',''],
	['salta','orán',''],
	['salta','payogasta',''],
	['salta','pichanal',''],
	['salta','prof. s. mazza',''],
	['salta','río piedras',''],
	['salta','rivadavia banda norte',''],
	['salta','rivadavia banda sur',''],
	['salta','rosario de la frontera',''],
	['salta','rosario de lerma',''],
	['salta','saclantás',''],
	['salta','18',''],
	['salta','san antonio',''],
	['salta','san carlos',''],
	['salta','san josé de metán',''],
	['salta','san ramón',''],
	['salta','santa victoria e.',''],
	['salta','santa victoria o.',''],
	['salta','tartagal',''],
	['salta','tolar grande',''],
	['salta','urundel',''],
	['salta','vaqueros',''],
	['salta','villa san lorenzo',''],
	['san juan','albardón',''],
	['san juan','angaco',''],
	['san juan','calingasta',''],
	['san juan','capital',''],
	['san juan','caucete',''],
	['san juan','chimbas',''],
	['san juan','iglesia',''],
	['san juan','jachal',''],
	['san juan','nueve de julio',''],
	['san juan','pocito',''],
	['san juan','rawson',''],
	['san juan','rivadavia',''],
	['san juan','19',''],
	['san juan','san martín',''],
	['san juan','santa lucía',''],
	['san juan','sarmiento',''],
	['san juan','ullum',''],
	['san juan','valle fértil',''],
	['san juan','veinticinco de mayo',''],
	['san juan','zonda',''],
	['san luis','alto pelado',''],
	['san luis','alto pencoso',''],
	['san luis','anchorena',''],
	['san luis','arizona',''],
	['san luis','bagual',''],
	['san luis','balde',''],
	['san luis','batavia',''],
	['san luis','beazley',''],
	['san luis','buena esperanza',''],
	['san luis','candelaria',''],
	['san luis','capital',''],
	['san luis','carolina',''],
	['san luis','carpintería',''],
	['san luis','concarán',''],
	['san luis','cortaderas',''],
	['san luis','el morro',''],
	['san luis','el trapiche',''],
	['san luis','el volcán',''],
	['san luis','fortín el patria',''],
	['san luis','fortuna',''],
	['san luis','fraga',''],
	['san luis','juan jorba',''],
	['san luis','juan llerena',''],
	['san luis','juana koslay',''],
	['san luis','justo daract',''],
	['san luis','la calera',''],
	['san luis','la florida',''],
	['san luis','la punilla',''],
	['san luis','la toma',''],
	['san luis','lafinur',''],
	['san luis','las aguadas',''],
	['san luis','las chacras',''],
	['san luis','las lagunas',''],
	['san luis','las vertientes',''],
	['san luis','lavaisse',''],
	['san luis','leandro n. alem',''],
	['san luis','los molles',''],
	['san luis','luján',''],
	['san luis','mercedes',''],
	['san luis','merlo',''],
	['san luis','naschel',''],
	['san luis','navia',''],
	['san luis','nogolí',''],
	['san luis','nueva galia',''],
	['san luis','papagayos',''],
	['san luis','paso grande',''],
	['san luis','potrero de los funes',''],
	['san luis','quines',''],
	['san luis','renca',''],
	['san luis','saladillo',''],
	['san luis','san francisco',''],
	['san luis','san gerónimo',''],
	['san luis','san martín',''],
	['san luis','san pablo',''],
	['san luis','santa rosa de conlara',''],
	['san luis','talita',''],
	['san luis','tilisarao',''],
	['san luis','unión',''],
	['san luis','villa de la quebrada',''],
	['san luis','villa de praga',''],
	['san luis','villa del carmen',''],
	['san luis','villa gral. roca',''],
	['san luis','villa larca',''],
	['san luis','villa mercedes',''],
	['san luis','zanjitas',''],
	['santa cruz','calafate',''],
	['santa cruz','caleta olivia',''],
	['santa cruz','cañadón seco',''],
	['santa cruz','comandante piedrabuena',''],
	['santa cruz','el calafate',''],
	['santa cruz','el chaltén',''],
	['santa cruz','gdor. gregores',''],
	['santa cruz','hipólito yrigoyen',''],
	['santa cruz','jaramillo',''],
	['santa cruz','koluel kaike',''],
	['santa cruz','las heras',''],
	['santa cruz','los antiguos',''],
	['santa cruz','perito moreno',''],
	['santa cruz','pico truncado',''],
	['santa cruz','pto. deseado',''],
	['santa cruz','pto. san julián',''],
	['santa cruz','pto. 21',''],
	['santa cruz','río cuarto',''],
	['santa cruz','río gallegos',''],
	['santa cruz','río turbio',''],
	['santa cruz','tres lagos',''],
	['santa cruz','veintiocho de noviembre',''],
	['santa fe','aarón castellanos',''],
	['santa fe','acebal',''],
	['santa fe','aguará grande',''],
	['santa fe','albarellos',''],
	['santa fe','alcorta',''],
	['santa fe','aldao',''],
	['santa fe','alejandra',''],
	['santa fe','álvarez',''],
	['santa fe','ambrosetti',''],
	['santa fe','amenábar',''],
	['santa fe','angélica',''],
	['santa fe','angeloni',''],
	['santa fe','arequito',''],
	['santa fe','arminda',''],
	['santa fe','armstrong',''],
	['santa fe','arocena',''],
	['santa fe','arroyo aguiar',''],
	['santa fe','arroyo ceibal',''],
	['santa fe','arroyo leyes',''],
	['santa fe','arroyo seco',''],
	['santa fe','arrufó',''],
	['santa fe','arteaga',''],
	['santa fe','ataliva',''],
	['santa fe','aurelia',''],
	['santa fe','avellaneda',''],
	['santa fe','barrancas',''],
	['santa fe','bauer y sigel',''],
	['santa fe','bella italia',''],
	['santa fe','berabevú',''],
	['santa fe','berna',''],
	['santa fe','bernardo de irigoyen',''],
	['santa fe','bigand',''],
	['santa fe','bombal',''],
	['santa fe','bouquet',''],
	['santa fe','bustinza',''],
	['santa fe','cabal',''],
	['santa fe','cacique ariacaiquin',''],
	['santa fe','cafferata',''],
	['santa fe','calchaquí',''],
	['santa fe','campo andino',''],
	['santa fe','campo piaggio',''],
	['santa fe','cañada de gómez',''],
	['santa fe','cañada del ucle',''],
	['santa fe','cañada rica',''],
	['santa fe','cañada rosquín',''],
	['santa fe','candioti',''],
	['santa fe','capital',''],
	['santa fe','capitán bermúdez',''],
	['santa fe','capivara',''],
	['santa fe','carcarañá',''],
	['santa fe','carlos pellegrini',''],
	['santa fe','carmen',''],
	['santa fe','carmen del sauce',''],
	['santa fe','carreras',''],
	['santa fe','carrizales',''],
	['santa fe','casalegno',''],
	['santa fe','casas',''],
	['santa fe','casilda',''],
	['santa fe','castelar',''],
	['santa fe','castellanos',''],
	['santa fe','cayastá',''],
	['santa fe','cayastacito',''],
	['santa fe','centeno',''],
	['santa fe','cepeda',''],
	['santa fe','ceres',''],
	['santa fe','chabás',''],
	['santa fe','chañar ladeado',''],
	['santa fe','chapuy',''],
	['santa fe','chovet',''],
	['santa fe','christophersen',''],
	['santa fe','classon',''],
	['santa fe','cnel. arnold',''],
	['santa fe','cnel. bogado',''],
	['santa fe','cnel. dominguez',''],
	['santa fe','cnel. fraga',''],
	['santa fe','col. aldao',''],
	['santa fe','col. ana',''],
	['santa fe','col. belgrano',''],
	['santa fe','col. bicha',''],
	['santa fe','col. bigand',''],
	['santa fe','col. bossi',''],
	['santa fe','col. cavour',''],
	['santa fe','col. cello',''],
	['santa fe','col. dolores',''],
	['santa fe','col. dos rosas',''],
	['santa fe','col. durán',''],
	['santa fe','col. iturraspe',''],
	['santa fe','col. margarita',''],
	['santa fe','col. mascias',''],
	['santa fe','col. raquel',''],
	['santa fe','col. rosa',''],
	['santa fe','col. san josé',''],
	['santa fe','constanza',''],
	['santa fe','coronda',''],
	['santa fe','correa',''],
	['santa fe','crispi',''],
	['santa fe','cululú',''],
	['santa fe','curupayti',''],
	['santa fe','desvio arijón',''],
	['santa fe','diaz',''],
	['santa fe','diego de alvear',''],
	['santa fe','egusquiza',''],
	['santa fe','el arazá',''],
	['santa fe','el rabón',''],
	['santa fe','el sombrerito',''],
	['santa fe','el trébol',''],
	['santa fe','elisa',''],
	['santa fe','elortondo',''],
	['santa fe','emilia',''],
	['santa fe','empalme san carlos',''],
	['santa fe','empalme villa constitucion',''],
	['santa fe','esmeralda',''],
	['santa fe','esperanza',''],
	['santa fe','estación alvear',''],
	['santa fe','estacion clucellas',''],
	['santa fe','esteban rams',''],
	['santa fe','esther',''],
	['santa fe','esustolia',''],
	['santa fe','eusebia',''],
	['santa fe','felicia',''],
	['santa fe','fidela',''],
	['santa fe','fighiera',''],
	['santa fe','firmat',''],
	['santa fe','florencia',''],
	['santa fe','fortín olmos',''],
	['santa fe','franck',''],
	['santa fe','fray luis beltrán',''],
	['santa fe','frontera',''],
	['santa fe','fuentes',''],
	['santa fe','funes',''],
	['santa fe','gaboto',''],
	['santa fe','galisteo',''],
	['santa fe','gálvez',''],
	['santa fe','garabalto',''],
	['santa fe','garibaldi',''],
	['santa fe','gato colorado',''],
	['santa fe','gdor. crespo',''],
	['santa fe','gessler',''],
	['santa fe','godoy',''],
	['santa fe','golondrina',''],
	['santa fe','gral. gelly',''],
	['santa fe','gral. lagos',''],
	['santa fe','granadero baigorria',''],
	['santa fe','gregoria perez de denis',''],
	['santa fe','grutly',''],
	['santa fe','guadalupe n.',''],
	['santa fe','gödeken',''],
	['santa fe','helvecia',''],
	['santa fe','hersilia',''],
	['santa fe','hipatía',''],
	['santa fe','huanqueros',''],
	['santa fe','hugentobler',''],
	['santa fe','hughes',''],
	['santa fe','humberto 1º',''],
	['santa fe','humboldt',''],
	['santa fe','ibarlucea',''],
	['santa fe','ing. chanourdie',''],
	['santa fe','intiyaco',''],
	['santa fe','ituzaingó',''],
	['santa fe','jacinto l. aráuz',''],
	['santa fe','josefina',''],
	['santa fe','juan b. molina',''],
	['santa fe','juan de garay',''],
	['santa fe','juncal',''],
	['santa fe','la brava',''],
	['santa fe','la cabral',''],
	['santa fe','la camila',''],
	['santa fe','la chispa',''],
	['santa fe','la clara',''],
	['santa fe','la criolla',''],
	['santa fe','la gallareta',''],
	['santa fe','la lucila',''],
	['santa fe','la pelada',''],
	['santa fe','la penca',''],
	['santa fe','la rubia',''],
	['santa fe','la sarita',''],
	['santa fe','la vanguardia',''],
	['santa fe','labordeboy',''],
	['santa fe','laguna paiva',''],
	['santa fe','landeta',''],
	['santa fe','lanteri',''],
	['santa fe','larrechea',''],
	['santa fe','las avispas',''],
	['santa fe','las bandurrias',''],
	['santa fe','las garzas',''],
	['santa fe','las palmeras',''],
	['santa fe','las parejas',''],
	['santa fe','las petacas',''],
	['santa fe','las rosas',''],
	['santa fe','las toscas',''],
	['santa fe','las tunas',''],
	['santa fe','lazzarino',''],
	['santa fe','lehmann',''],
	['santa fe','llambi campbell',''],
	['santa fe','logroño',''],
	['santa fe','loma alta',''],
	['santa fe','lópez',''],
	['santa fe','los amores',''],
	['santa fe','los cardos',''],
	['santa fe','los laureles',''],
	['santa fe','los molinos',''],
	['santa fe','los quirquinchos',''],
	['santa fe','lucio v. lopez',''],
	['santa fe','luis palacios',''],
	['santa fe','ma. juana',''],
	['santa fe','ma. luisa',''],
	['santa fe','ma. susana',''],
	['santa fe','ma. teresa',''],
	['santa fe','maciel',''],
	['santa fe','maggiolo',''],
	['santa fe','malabrigo',''],
	['santa fe','marcelino escalada',''],
	['santa fe','margarita',''],
	['santa fe','matilde',''],
	['santa fe','mauá',''],
	['santa fe','máximo paz',''],
	['santa fe','melincué',''],
	['santa fe','miguel torres',''],
	['santa fe','moisés ville',''],
	['santa fe','monigotes',''],
	['santa fe','monje',''],
	['santa fe','monte obscuridad',''],
	['santa fe','monte vera',''],
	['santa fe','montefiore',''],
	['santa fe','montes de oca',''],
	['santa fe','murphy',''],
	['santa fe','ñanducita',''],
	['santa fe','naré',''],
	['santa fe','nelson',''],
	['santa fe','nicanor e. molinas',''],
	['santa fe','nuevo torino',''],
	['santa fe','oliveros',''],
	['santa fe','palacios',''],
	['santa fe','pavón',''],
	['santa fe','pavón arriba',''],
	['santa fe','pedro gómez cello',''],
	['santa fe','pérez',''],
	['santa fe','peyrano',''],
	['santa fe','piamonte',''],
	['santa fe','pilar',''],
	['santa fe','piñero',''],
	['santa fe','plaza clucellas',''],
	['santa fe','portugalete',''],
	['santa fe','pozo borrado',''],
	['santa fe','progreso',''],
	['santa fe','providencia',''],
	['santa fe','pte. roca',''],
	['santa fe','pueblo andino',''],
	['santa fe','pueblo esther',''],
	['santa fe','pueblo gral. san martín',''],
	['santa fe','pueblo irigoyen',''],
	['santa fe','pueblo marini',''],
	['santa fe','pueblo muñoz',''],
	['santa fe','pueblo uranga',''],
	['santa fe','pujato',''],
	['santa fe','pujato n.',''],
	['santa fe','rafaela',''],
	['santa fe','ramayón',''],
	['santa fe','ramona',''],
	['santa fe','reconquista',''],
	['santa fe','recreo',''],
	['santa fe','ricardone',''],
	['santa fe','rivadavia',''],
	['santa fe','roldán',''],
	['santa fe','romang',''],
	['santa fe','rosario',''],
	['santa fe','rueda',''],
	['santa fe','rufino',''],
	['santa fe','sa pereira',''],
	['santa fe','saguier',''],
	['santa fe','saladero m. cabal',''],
	['santa fe','salto grande',''],
	['santa fe','san agustín',''],
	['santa fe','san antonio de obligado',''],
	['santa fe','san bernardo (n.j.)',''],
	['santa fe','san bernardo (s.j.)',''],
	['santa fe','san carlos centro',''],
	['santa fe','san carlos n.',''],
	['santa fe','san carlos s.',''],
	['santa fe','san cristóbal',''],
	['santa fe','san eduardo',''],
	['santa fe','san eugenio',''],
	['santa fe','san fabián',''],
	['santa fe','san fco. de santa fé',''],
	['santa fe','san genaro',''],
	['santa fe','san genaro n.',''],
	['santa fe','san gregorio',''],
	['santa fe','san guillermo',''],
	['santa fe','san javier',''],
	['santa fe','san jerónimo del sauce',''],
	['santa fe','san jerónimo n.',''],
	['santa fe','san jerónimo s.',''],
	['santa fe','san jorge',''],
	['santa fe','san josé de la esquina',''],
	['santa fe','san josé del rincón',''],
	['santa fe','san justo',''],
	['santa fe','san lorenzo',''],
	['santa fe','san mariano',''],
	['santa fe','san martín de las escobas',''],
	['santa fe','san martín n.',''],
	['santa fe','san vicente',''],
	['santa fe','sancti spititu',''],
	['santa fe','sanford',''],
	['santa fe','santo domingo',''],
	['santa fe','santo tomé',''],
	['santa fe','santurce',''],
	['santa fe','sargento cabral',''],
	['santa fe','sarmiento',''],
	['santa fe','sastre',''],
	['santa fe','sauce viejo',''],
	['santa fe','serodino',''],
	['santa fe','silva',''],
	['santa fe','soldini',''],
	['santa fe','soledad',''],
	['santa fe','soutomayor',''],
	['santa fe','sta. clara de buena vista',''],
	['santa fe','sta. clara de saguier',''],
	['santa fe','sta. isabel',''],
	['santa fe','sta. margarita',''],
	['santa fe','sta. maria centro',''],
	['santa fe','sta. maría n.',''],
	['santa fe','sta. rosa',''],
	['santa fe','sta. teresa',''],
	['santa fe','suardi',''],
	['santa fe','sunchales',''],
	['santa fe','susana',''],
	['santa fe','tacuarendí',''],
	['santa fe','tacural',''],
	['santa fe','tartagal',''],
	['santa fe','teodelina',''],
	['santa fe','theobald',''],
	['santa fe','timbúes',''],
	['santa fe','toba',''],
	['santa fe','tortugas',''],
	['santa fe','tostado',''],
	['santa fe','totoras',''],
	['santa fe','traill',''],
	['santa fe','venado tuerto',''],
	['santa fe','vera',''],
	['santa fe','vera y pintado',''],
	['santa fe','videla',''],
	['santa fe','vila',''],
	['santa fe','villa amelia',''],
	['santa fe','villa ana',''],
	['santa fe','villa cañas',''],
	['santa fe','villa constitución',''],
	['santa fe','villa eloísa',''],
	['santa fe','villa gdor. gálvez',''],
	['santa fe','villa guillermina',''],
	['santa fe','villa minetti',''],
	['santa fe','villa mugueta',''],
	['santa fe','villa ocampo',''],
	['santa fe','villa san josé',''],
	['santa fe','villa saralegui',''],
	['santa fe','villa trinidad',''],
	['santa fe','villada',''],
	['santa fe','virginia',''],
	['santa fe','wheelwright',''],
	['santa fe','zavalla',''],
	['santa fe','zenón pereira',''],
	['santiago del estero','añatuya',''],
	['santiago del estero','árraga',''],
	['santiago del estero','bandera',''],
	['santiago del estero','bandera bajada',''],
	['santiago del estero','beltrán',''],
	['santiago del estero','brea pozo',''],
	['santiago del estero','campo gallo',''],
	['santiago del estero','capital',''],
	['santiago del estero','chilca juliana',''],
	['santiago del estero','choya',''],
	['santiago del estero','clodomira',''],
	['santiago del estero','col. alpina',''],
	['santiago del estero','col. dora',''],
	['santiago del estero','col. el simbolar robles',''],
	['santiago del estero','el bobadal',''],
	['santiago del estero','el charco',''],
	['santiago del estero','el mojón',''],
	['santiago del estero','estación atamisqui',''],
	['santiago del estero','estación simbolar',''],
	['santiago del estero','fernández',''],
	['santiago del estero','fortín inca',''],
	['santiago del estero','frías',''],
	['santiago del estero','garza',''],
	['santiago del estero','gramilla',''],
	['santiago del estero','guardia escolta',''],
	['santiago del estero','herrera',''],
	['santiago del estero','icaño',''],
	['santiago del estero','ing. forres',''],
	['santiago del estero','la banda',''],
	['santiago del estero','la cañada',''],
	['santiago del estero','laprida',''],
	['santiago del estero','lavalle',''],
	['santiago del estero','loreto',''],
	['santiago del estero','los juríes',''],
	['santiago del estero','los núñez',''],
	['santiago del estero','los pirpintos',''],
	['santiago del estero','los quiroga',''],
	['santiago del estero','los telares',''],
	['santiago del estero','lugones',''],
	['santiago del estero','malbrán',''],
	['santiago del estero','matara',''],
	['santiago del estero','medellín',''],
	['santiago del estero','monte quemado',''],
	['santiago del estero','nueva esperanza',''],
	['santiago del estero','nueva francia',''],
	['santiago del estero','palo negro',''],
	['santiago del estero','pampa de los guanacos',''],
	['santiago del estero','pinto',''],
	['santiago del estero','pozo hondo',''],
	['santiago del estero','quimilí',''],
	['santiago del estero','real sayana',''],
	['santiago del estero','sachayoj',''],
	['santiago del estero','san pedro de guasayán',''],
	['santiago del estero','selva',''],
	['santiago del estero','sol de julio',''],
	['santiago del estero','sumampa',''],
	['santiago del estero','suncho corral',''],
	['santiago del estero','taboada',''],
	['santiago del estero','tapso',''],
	['santiago del estero','termas de rio hondo',''],
	['santiago del estero','tintina',''],
	['santiago del estero','tomas young',''],
	['santiago del estero','vilelas',''],
	['santiago del estero','villa atamisqui',''],
	['santiago del estero','villa la punta',''],
	['santiago del estero','villa ojo de agua',''],
	['santiago del estero','villa río hondo',''],
	['santiago del estero','villa salavina',''],
	['santiago del estero','villa unión',''],
	['santiago del estero','vilmer',''],
	['santiago del estero','weisburd',''],
	['tierra del fuego','río grande',''],
	['tierra del fuego','tolhuin',''],
	['tierra del fuego','ushuaia',''],
	['tucumán','acheral',''],
	['tucumán','agua dulce',''],
	['tucumán','aguilares',''],
	['tucumán','alderetes',''],
	['tucumán','alpachiri',''],
	['tucumán','alto verde',''],
	['tucumán','amaicha del valle',''],
	['tucumán','amberes',''],
	['tucumán','ancajuli',''],
	['tucumán','arcadia',''],
	['tucumán','atahona',''],
	['tucumán','banda del río sali',''],
	['tucumán','bella vista',''],
	['tucumán','buena vista',''],
	['tucumán','burruyacú',''],
	['tucumán','capitán cáceres',''],
	['tucumán','cevil redondo',''],
	['tucumán','choromoro',''],
	['tucumán','ciudacita',''],
	['tucumán','colalao del valle',''],
	['tucumán','colombres',''],
	['tucumán','concepción',''],
	['tucumán','delfín gallo',''],
	['tucumán','el bracho',''],
	['tucumán','el cadillal',''],
	['tucumán','el cercado',''],
	['tucumán','el chañar',''],
	['tucumán','el manantial',''],
	['tucumán','el mojón',''],
	['tucumán','el mollar',''],
	['tucumán','el naranjito',''],
	['tucumán','el naranjo',''],
	['tucumán','el polear',''],
	['tucumán','el puestito',''],
	['tucumán','el sacrificio',''],
	['tucumán','el timbó',''],
	['tucumán','escaba',''],
	['tucumán','esquina',''],
	['tucumán','estación aráoz',''],
	['tucumán','famaillá',''],
	['tucumán','gastone',''],
	['tucumán','gdor. garmendia',''],
	['tucumán','gdor. piedrabuena',''],
	['tucumán','graneros',''],
	['tucumán','huasa pampa',''],
	['tucumán','j. b. alberdi',''],
	['tucumán','la cocha',''],
	['tucumán','la esperanza',''],
	['tucumán','la florida',''],
	['tucumán','la ramada',''],
	['tucumán','la trinidad',''],
	['tucumán','lamadrid',''],
	['tucumán','las cejas',''],
	['tucumán','las talas',''],
	['tucumán','las talitas',''],
	['tucumán','los bulacio',''],
	['tucumán','los gómez',''],
	['tucumán','los nogales',''],
	['tucumán','los pereyra',''],
	['tucumán','los pérez',''],
	['tucumán','los puestos',''],
	['tucumán','los ralos',''],
	['tucumán','los sarmientos',''],
	['tucumán','los sosa',''],
	['tucumán','lules',''],
	['tucumán','m. garcía fernández',''],
	['tucumán','manuela pedraza',''],
	['tucumán','medinas',''],
	['tucumán','monte bello',''],
	['tucumán','monteagudo',''],
	['tucumán','monteros',''],
	['tucumán','padre monti',''],
	['tucumán','pampa mayo',''],
	['tucumán','quilmes',''],
	['tucumán','raco',''],
	['tucumán','ranchillos',''],
	['tucumán','río chico',''],
	['tucumán','río colorado',''],
	['tucumán','río seco',''],
	['tucumán','rumi punco',''],
	['tucumán','san andrés',''],
	['tucumán','san felipe',''],
	['tucumán','san ignacio',''],
	['tucumán','san javier',''],
	['tucumán','san josé',''],
	['tucumán','san miguel de 25',''],
	['tucumán','san pedro',''],
	['tucumán','san pedro de colalao',''],
	['tucumán','santa rosa de leales',''],
	['tucumán','sgto. moya',''],
	['tucumán','siete de abril',''],
	['tucumán','simoca',''],
	['tucumán','soldado maldonado',''],
	['tucumán','sta. ana',''],
	['tucumán','sta. cruz',''],
	['tucumán','sta. lucía',''],
	['tucumán','taco ralo',''],
	['tucumán','tafí del valle',''],
	['tucumán','tafí viejo',''],
	['tucumán','tapia',''],
	['tucumán','teniente berdina',''],
	['tucumán','trancas',''],
	['tucumán','villa belgrano',''],
	['tucumán','villa benjamín araoz',''],
	['tucumán','villa chiligasta',''],
	['tucumán','villa de leales',''],
	['tucumán','villa quinteros',''],
	['tucumán','yánima',''],
	['tucumán','yerba buena',''],
	['tucumán','yerba buena (s)','']
];