<?php //Paises Init
$payload = [
    ['0','afganistán','{"code":"AF","iso3":"AFG","name":"Afghanistan"}'],
    ['0','albania','{"code":"AL","iso3":"ALB","name":"Albania"}'],
    ['0','alemania','{"code":"DE","iso3":"DEU","name":"Germany"}'],
    ['0','algeria','{"code":"DZ","iso3":"DZA","name":"Algeria"}'],
    ['0','andorra','{"code":"AD","iso3":"AND","name":"Andorra"}'],
    ['0','angola','{"code":"AO","iso3":"AGO","name":"Angola"}'],
    ['0','anguila','{"code":"AI","iso3":"AIA","name":"Anguilla"}'],
    ['0','antártida','{"code":"AQ","iso3":"ATA","name":"Antarctica"}'],
    ['0','antigua y barbuda','{"code":"AG","iso3":"ATG","name":"Antigua and Barbuda"}'],
    ['0','antillas holandesas','{"code":"AN","iso3":"ANT","name":"Netherlands Antilles"}'],
    ['0','arabia saudita','{"code":"SA","iso3":"SAU","name":"Saudi Arabia"}'],
    ['0','argentina','{"code":"AR","iso3":"ARG","name":"Argentina"}'],
    ['0','armenia','{"code":"AM","iso3":"ARM","name":"Armenia"}'],
    ['0','aruba','{"code":"AW","iso3":"ABW","name":"Aruba"}'],
    ['0','australia','{"code":"AU","iso3":"AUS","name":"Australia"}'],
    ['0','austria','{"code":"AT","iso3":"AUT","name":"Austria"}'],
    ['0','azerbayán','{"code":"AZ","iso3":"AZE","name":"Azerbaijan"}'],
    ['0','bélgica','{"code":"BE","iso3":"BEL","name":"Belgium"}'],
    ['0','bahamas','{"code":"BS","iso3":"BHS","name":"Bahamas"}'],
    ['0','bahrein','{"code":"BH","iso3":"BHR","name":"Bahrain"}'],
    ['0','bangladesh','{"code":"BD","iso3":"BGD","name":"Bangladesh"}'],
    ['0','barbados','{"code":"BB","iso3":"BRB","name":"Barbados"}'],
    ['0','belice','{"code":"BZ","iso3":"BLZ","name":"Belize"}'],
    ['0','benín','{"code":"BJ","iso3":"BEN","name":"Benin"}'],
    ['0','bhután','{"code":"BT","iso3":"BTN","name":"Bhutan"}'],
    ['0','bielorrusia','{"code":"BY","iso3":"BLR","name":"Belarus"}'],
    ['0','birmania','{"code":"MM","iso3":"MMR","name":"Myanmar"}'],
    ['0','bolivia','{"code":"BO","iso3":"BOL","name":"Bolivia"}'],
    ['0','bosnia y herzegovina','{"code":"BA","iso3":"BIH","name":"Bosniaand Herzegovina"}'],
    ['0','botsuana','{"code":"BW","iso3":"BWA","name":"Botswana"}'],
    ['0','brasil','{"code":"BR","iso3":"BRA","name":"Brazil"}'],
    ['0','brunéi','{"code":"BN","iso3":"BRN","name":"Brunei"}'],
    ['0','bulgaria','{"code":"BG","iso3":"BGR","name":"Bulgaria"}'],
    ['0','burkinafaso','{"code":"BF","iso3":"BFA","name":"BurkinaFaso"}'],
    ['0','burundi','{"code":"BI","iso3":"BDI","name":"Burundi"}'],
    ['0','caboverde','{"code":"CV","iso3":"CPV","name":"CapeVerde"}'],
    ['0','camboya','{"code":"KH","iso3":"KHM","name":"Cambodia"}'],
    ['0','camerún','{"code":"CM","iso3":"CMR","name":"Cameroon"}'],
    ['0','canadá','{"code":"CA","iso3":"CAN","name":"Canada"}'],
    ['0','chad','{"code":"TD","iso3":"TCD","name":"Chad"}'],
    ['0','chile','{"code":"CL","iso3":"CHL","name":"Chile"}'],
    ['0','china','{"code":"CN","iso3":"CHN","name":"China"}'],
    ['0','chipre','{"code":"CY","iso3":"CYP","name":"Cyprus"}'],
    ['0','ciudad del vaticano','{"code":"VA","iso3":"VAT","name":"Vatican City State"}'],
    ['0','colombia','{"code":"CO","iso3":"COL","name":"Colombia"}'],
    ['0','comoras','{"code":"KM","iso3":"COM","name":"Comoros"}'],
    ['0','congo','{"code":"CG","iso3":"COG","name":"Congo"}'],
    ['0','corea del norte','{"code":"KP","iso3":"PRK","name":"North Korea"}'],
    ['0','corea del sur','{"code":"KR","iso3":"KOR","name":"South Korea"}'],
    ['0','costa de marfil','{"code":"CI","iso3":"CIV","name":"Ivory Coast"}'],
    ['0','costa rica','{"code":"CR","iso3":"CRI","name":"Costa Rica"}'],
    ['0','croacia','{"code":"HR","iso3":"HRV","name":"Croatia"}'],
    ['0','cuba','{"code":"CU","iso3":"CUB","name":"Cuba"}'],
    ['0','dinamarca','{"code":"DK","iso3":"DNK","name":"Denmark"}'],
    ['0','dominica','{"code":"DM","iso3":"DMA","name":"Dominica"}'],
    ['0','ecuador','{"code":"EC","iso3":"ECU","name":"Ecuador"}'],
    ['0','egipto','{"code":"EG","iso3":"EGY","name":"Egypt"}'],
    ['0','el salvador','{"code":"SV","iso3":"SLV","name":"El Salvador"}'],
    ['0','emiratos árabes unidos','{"code":"AE","iso3":"ARE","name":"United Arab Emirates"}'],
    ['0','eritrea','{"code":"ER","iso3":"ERI","name":"Eritrea"}'],
    ['0','eslovaquia','{"code":"SK","iso3":"SVK","name":"Slovakia"}'],
    ['0','eslovenia','{"code":"SI","iso3":"SVN","name":"Slovenia"}'],
    ['0','españa','{"code":"ES","iso3":"ESP","name":"Spain"}'],
    ['0','estados unidos de américa','{"code":"US","iso3":"USA","name":"United States of America"}'],
    ['0','estonia','{"code":"EE","iso3":"EST","name":"Estonia"}'],
    ['0','etiopía','{"code":"ET","iso3":"ETH","name":"Ethiopia"}'],
    ['0','filipinas','{"code":"PH","iso3":"PHL","name":"Philippines"}'],
    ['0','finlandia','{"code":"FI","iso3":"FIN","name":"Finland"}'],
    ['0','fiyi','{"code":"FJ","iso3":"FJI","name":"Fiji"}'],
    ['0','francia','{"code":"FR","iso3":"FRA","name":"France"}'],
    ['0','gabón','{"code":"GA","iso3":"GAB","name":"Gabon"}'],
    ['0','gambia','{"code":"GM","iso3":"GMB","name":"Gambia"}'],
    ['0','georgia','{"code":"GE","iso3":"GEO","name":"Georgia"}'],
    ['0','ghana','{"code":"GH","iso3":"GHA","name":"Ghana"}'],
    ['0','gibraltar','{"code":"GI","iso3":"GIB","name":"Gibraltar"}'],
    ['0','granada','{"code":"GD","iso3":"GRD","name":"Grenada"}'],
    ['0','grecia','{"code":"GR","iso3":"GRC","name":"Greece"}'],
    ['0','groenlandia','{"code":"GL","iso3":"GRL","name":"Greenland"}'],
    ['0','guadalupe','{"code":"GP","iso3":"GLP","name":"Guadeloupe"}'],
    ['0','guam','{"code":"GU","iso3":"GUM","name":"Guam"}'],
    ['0','guatemala','{"code":"GT","iso3":"GTM","name":"Guatemala"}'],
    ['0','guayana francesa','{"code":"GF","iso3":"GUF","name":"French Guiana"}'],
    ['0','guernsey','{"code":"GG","iso3":"GGY","name":"Guernsey"}'],
    ['0','guinea','{"code":"GN","iso3":"GIN","name":"Guinea"}'],
    ['0','guineaecuatorial','{"code":"GQ","iso3":"GNQ","name":"Equatorial Guinea"}'],
    ['0','guinea-bissau','{"code":"GW","iso3":"GNB","name":"Guinea-Bissau"}'],
    ['0','guyana','{"code":"GY","iso3":"GUY","name":"Guyana"}'],
    ['0','haití','{"code":"HT","iso3":"HTI","name":"Haiti"}'],
    ['0','honduras','{"code":"HN","iso3":"HND","name":"Honduras"}'],
    ['0','hongkong','{"code":"HK","iso3":"HKG","name":"HongKong"}'],
    ['0','hungría','{"code":"HU","iso3":"HUN","name":"Hungary"}'],
    ['0','india','{"code":"IN","iso3":"IND","name":"India"}'],
    ['0','indonesia','{"code":"ID","iso3":"IDN","name":"Indonesia"}'],
    ['0','irán','{"code":"IR","iso3":"IRN","name":"Iran"}'],
    ['0','irak','{"code":"IQ","iso3":"IRQ","name":"Iraq"}'],
    ['0','irlanda','{"code":"IE","iso3":"IRL","name":"Ireland"}'],
    ['0','isla bouvet','{"code":"BV","iso3":"BVT","name":"Bouvet Island"}'],
    ['0','isla de man','{"code":"IM","iso3":"IMN","name":"Isle of Man"}'],
    ['0','isla de navidad','{"code":"CX","iso3":"CXR","name":"Christmas Island"}'],
    ['0','isla norfolk','{"code":"NF","iso3":"NFK","name":"Norfolk Island"}'],
    ['0','islandia','{"code":"IS","iso3":"ISL","name":"Iceland"}'],
    ['0','islas bermudas','{"code":"BM","iso3":"BMU","name":"Bermuda Islands"}'],
    ['0','islas caimán','{"code":"KY","iso3":"CYM","name":"Cayman Islands"}'],
    ['0','islas cocos(keeling)','{"code":"CC","iso3":"CCK","name":"Cocos (Keeling) Islands"}'],
    ['0','islas cook','{"code":"CK","iso3":"COK","name":"Cook Islands"}'],
    ['0','islas de åland','{"code":"AX","iso3":"ALA","name":"\\u00c5landIslands"}'],
    ['0','islas feroe','{"code":"FO","iso3":"FRO","name":"FaroeIslands"}'],
    ['0','islas georgias del sur y sandwich del sur','{"code":"GS","iso3":"SGS","name":"South Georgia and the South Sandwich Islands"}'],
    ['0','islas heard y mcdonald','{"code":"HM","iso3":"HMD","name":"Heard Island and McDonald Islands"}'],
    ['0','islas maldivas','{"code":"MV","iso3":"MDV","name":"Maldives"}'],
    ['0','islas malvinas','{"code":"FK","iso3":"FLK","name":"Falkl and Islands (Malvinas)"}'],
    ['0','islas marianas del norte','{"code":"MP","iso3":"MNP","name":"Northern Mariana Islands"}'],
    ['0','islas marshall','{"code":"MH","iso3":"MHL","name":"Marshall Islands"}'],
    ['0','islas pitcairn','{"code":"PN","iso3":"PCN","name":"Pitcairn Islands"}'],
    ['0','islas salomón','{"code":"SB","iso3":"SLB","name":"Solomon Islands"}'],
    ['0','islas turcas y caicos','{"code":"TC","iso3":"TCA","name":"Turksand Caicos Islands"}'],
    ['0','islas ultramarinas menores de estados unidos','{"code":"UM","iso3":"UMI","name":"United States Minor Outlying Islands"}'],
    ['0','islas vírgenes británicas','{"code":"VG","iso3":"VG","name":"Virgin Islands"}'],
    ['0','islas vírgenes de los estados unidos','{"code":"VI","iso3":"VIR","name":"United States Virgin Islands"}'],
    ['0','israel','{"code":"IL","iso3":"ISR","name":"Israel"}'],
    ['0','italia','{"code":"IT","iso3":"ITA","name":"Italy"}'],
    ['0','jamaica','{"code":"JM","iso3":"JAM","name":"Jamaica"}'],
    ['0','japón','{"code":"JP","iso3":"JPN","name":"Japan"}'],
    ['0','jersey','{"code":"JE","iso3":"JEY","name":"Jersey"}'],
    ['0','jordania','{"code":"JO","iso3":"JOR","name":"Jordan"}'],
    ['0','kazajistán','{"code":"KZ","iso3":"KAZ","name":"Kazakhstan"}'],
    ['0','kenia','{"code":"KE","iso3":"KEN","name":"Kenya"}'],
    ['0','kirgizstán','{"code":"KG","iso3":"KGZ","name":"Kyrgyzstan"}'],
    ['0','kiribati','{"code":"KI","iso3":"KIR","name":"Kiribati"}'],
    ['0','kuwait','{"code":"KW","iso3":"KWT","name":"Kuwait"}'],
    ['0','líbano','{"code":"LB","iso3":"LBN","name":"Lebanon"}'],
    ['0','laos','{"code":"LA","iso3":"LAO","name":"Laos"}'],
    ['0','lesoto','{"code":"LS","iso3":"LSO","name":"Lesotho"}'],
    ['0','letonia','{"code":"LV","iso3":"LVA","name":"Latvia"}'],
    ['0','liberia','{"code":"LR","iso3":"LBR","name":"Liberia"}'],
    ['0','libia','{"code":"LY","iso3":"LBY","name":"Libya"}'],
    ['0','liechtenstein','{"code":"LI","iso3":"LIE","name":"Liechtenstein"}'],
    ['0','lituania','{"code":"LT","iso3":"LTU","name":"Lithuania"}'],
    ['0','luxemburgo','{"code":"LU","iso3":"LUX","name":"Luxembourg"}'],
    ['0','méxico','{"code":"MX","iso3":"MEX","name":"Mexico"}'],
    ['0','mónaco','{"code":"MC","iso3":"MCO","name":"Monaco"}'],
    ['0','macao','{"code":"MO","iso3":"MAC","name":"Macao"}'],
    ['0','macedônia','{"code":"MK","iso3":"MKD","name":"Macedonia"}'],
    ['0','madagascar','{"code":"MG","iso3":"MDG","name":"Madagascar"}'],
    ['0','malasia','{"code":"MY","iso3":"MYS","name":"Malaysia"}'],
    ['0','malawi','{"code":"MW","iso3":"MWI","name":"Malawi"}'],
    ['0','mali','{"code":"ML","iso3":"MLI","name":"Mali"}'],
    ['0','malta','{"code":"MT","iso3":"MLT","name":"Malta"}'],
    ['0','marruecos','{"code":"MA","iso3":"MAR","name":"Morocco"}'],
    ['0','martinica','{"code":"MQ","iso3":"MTQ","name":"Martinique"}'],
    ['0','mauricio','{"code":"MU","iso3":"MUS","name":"Mauritius"}'],
    ['0','mauritania','{"code":"MR","iso3":"MRT","name":"Mauritania"}'],
    ['0','mayotte','{"code":"YT","iso3":"MYT","name":"Mayotte"}'],
    ['0','micronesia','{"code":"FM","iso3":"FSM","name":"micronesia"}'],
    ['0','moldavia','{"code":"MD","iso3":"MDA","name":"Moldova"}'],
    ['0','mongolia','{"code":"MN","iso3":"MNG","name":"Mongolia"}'],
    ['0','montenegro','{"code":"ME","iso3":"MNE","name":"Montenegro"}'],
    ['0','montserrat','{"code":"MS","iso3":"MSR","name":"Montserrat"}'],
    ['0','mozambique','{"code":"MZ","iso3":"MOZ","name":"Mozambique"}'],
    ['0','namibia','{"code":"NA","iso3":"NAM","name":"Namibia"}'],
    ['0','nauru','{"code":"NR","iso3":"NRU","name":"Nauru"}'],
    ['0','nepal','{"code":"NP","iso3":"NPL","name":"Nepal"}'],
    ['0','nicaragua','{"code":"NI","iso3":"NIC","name":"Nicaragua"}'],
    ['0','niger','{"code":"NE","iso3":"NER","name":"Niger"}'],
    ['0','nigeria','{"code":"NG","iso3":"NGA","name":"Nigeria"}'],
    ['0','niue','{"code":"NU","iso3":"NIU","name":"Niue"}'],
    ['0','noruega','{"code":"NO","iso3":"NOR","name":"Norway"}'],
    ['0','nueva caledonia','{"code":"NC","iso3":"NCL","name":"New Caledonia"}'],
    ['0','nueva zelanda','{"code":"NZ","iso3":"NZL","name":"New Zealand"}'],
    ['0','omán','{"code":"OM","iso3":"OMN","name":"Oman"}'],
    ['0','países bajos','{"code":"NL","iso3":"NLD","name":"Netherlands"}'],
    ['0','pakistán','{"code":"PK","iso3":"PAK","name":"Pakistan"}'],
    ['0','palau','{"code":"PW","iso3":"PLW","name":"Palau"}'],
    ['0','palestina','{"code":"PS","iso3":"PSE","name":"Palestine"}'],
    ['0','panamá','{"code":"PA","iso3":"PAN","name":"Panama"}'],
    ['0','papúa nueva guinea','{"code":"PG","iso3":"PNG","name":"Papua New Guinea"}'],
    ['0','paraguay','{"code":"PY","iso3":"PRY","name":"Paraguay"}'],
    ['0','perú','{"code":"PE","iso3":"PER","name":"Peru"}'],
    ['0','polinesia francesa','{"code":"PF","iso3":"PYF","name":"French Polynesia"}'],
    ['0','polonia','{"code":"PL","iso3":"POL","name":"Poland"}'],
    ['0','portugal','{"code":"PT","iso3":"PRT","name":"Portugal"}'],
    ['0','puerto rico','{"code":"PR","iso3":"PRI","name":"Puerto Rico"}'],
    ['0','qatar','{"code":"QA","iso3":"QAT","name":"Qatar"}'],
    ['0','reino unido','{"code":"GB","iso3":"GBR","name":"United Kingdom"}'],
    ['0','república centro africana','{"code":"CF","iso3":"CAF","name":"Central African Republic"}'],
    ['0','república checa','{"code":"CZ","iso3":"CZE","name":"CzechRepublic"}'],
    ['0','repúblicadominicana','{"code":"DO","iso3":"DOM","name":"Dominican Republic"}'],
    ['0','reunión','{"code":"RE","iso3":"REU","name":"R\\u00e9union"}'],
    ['0','ruanda','{"code":"RW","iso3":"RWA","name":"Rwanda"}'],
    ['0','rumanía','{"code":"RO","iso3":"ROU","name":"Romania"}'],
    ['0','rusia','{"code":"RU","iso3":"RUS","name":"Russia"}'],
    ['0','sahara occidental','{"code":"EH","iso3":"ESH","name":"Western Sahara"}'],
    ['0','samoa','{"code":"WS","iso3":"WSM","name":"Samoa"}'],
    ['0','samoa americana','{"code":"AS","iso3":"ASM","name":"American Samoa"}'],
    ['0','san bartolomé','{"code":"BL","iso3":"BLM","name":"SaintBarth\\u00e9lemy"}'],
    ['0','san cristóbal y nieves','{"code":"KN","iso3":"KNA","name":"SaintKittsandNevis"}'],
    ['0','san marino','{"code":"SM","iso3":"SMR","name":"SanMarino"}'],
    ['0','san martín (francia)','{"code":"MF","iso3":"MAF","name":"Saint Martin (Frenchpart)"}'],
    ['0','san pedro y miquelón','{"code":"PM","iso3":"SPM","name":"Saint Pierreand Miquelon"}'],
    ['0','san vicente y las granadinas','{"code":"VC","iso3":"VCT","name":"Saint Vincent and the Grenadines"}'],
    ['0','santa elena','{"code":"SH","iso3":"SHN","name":"Ascensi\\u00f3nyTrist\\u00e1ndeAcu\\u00f1a"}'],
    ['0','santa lucía','{"code":"LC","iso3":"LCA","name":"SaintLucia"}'],
    ['0','santo tomé y príncipe','{"code":"ST","iso3":"STP","name":"Sao Tome and Principe"}'],
    ['0','senegal','{"code":"SN","iso3":"SEN","name":"Senegal"}'],
    ['0','serbia','{"code":"RS","iso3":"SRB","name":"Serbia"}'],
    ['0','seychelles','{"code":"SC","iso3":"SYC","name":"Seychelles"}'],
    ['0','sierra leona','{"code":"SL","iso3":"SLE","name":"Sierra Leone"}'],
    ['0','singapur','{"code":"SG","iso3":"SGP","name":"Singapore"}'],
    ['0','siria','{"code":"SY","iso3":"SYR","name":"Syria"}'],
    ['0','somalia','{"code":"SO","iso3":"SOM","name":"Somalia"}'],
    ['0','srilanka','{"code":"LK","iso3":"LKA","name":"SriLanka"}'],
    ['0','sudáfrica','{"code":"ZA","iso3":"ZAF","name":"South Africa"}'],
    ['0','sudán','{"code":"SD","iso3":"SDN","name":"Sudan"}'],
    ['0','suecia','{"code":"SE","iso3":"SWE","name":"Sweden"}'],
    ['0','suiza','{"code":"CH","iso3":"CHE","name":"Switzerland"}'],
    ['0','surinám','{"code":"SR","iso3":"SUR","name":"Suriname"}'],
    ['0','svalbard y janmayen','{"code":"SJ","iso3":"SJM","name":"Svalbardand Jan Mayen"}'],
    ['0','swazilandia','{"code":"SZ","iso3":"SWZ","name":"Swaziland"}'],
    ['0','tadjikistán','{"code":"TJ","iso3":"TJK","name":"Tajikistan"}'],
    ['0','tailandia','{"code":"TH","iso3":"THA","name":"Thailand"}'],
    ['0','taiwán','{"code":"TW","iso3":"TWN","name":"Taiwan"}'],
    ['0','tanzania','{"code":"TZ","iso3":"TZA","name":"Tanzania"}'],
    ['0','territorio británico del océano índico','{"code":"IO","iso3":"IOT","name":"British Indian Ocean Territory"}'],
    ['0','territorios australes y antárticas franceses','{"code":"TF","iso3":"ATF","name":"French Southern Territories"}'],
    ['0','timororiental','{"code":"TL","iso3":"TLS","name":"EastTimor"}'],
    ['0','togo','{"code":"TG","iso3":"TGO","name":"Togo"}'],
    ['0','tokelau','{"code":"TK","iso3":"TKL","name":"Tokelau"}'],
    ['0','tonga','{"code":"TO","iso3":"TON","name":"Tonga"}'],
    ['0','trinidad y tobago','{"code":"TT","iso3":"TTO","name":"Trinidad and Tobago"}'],
    ['0','tunez','{"code":"TN","iso3":"TUN","name":"Tunisia"}'],
    ['0','turkmenistán','{"code":"TM","iso3":"TKM","name":"Turkmenistan"}'],
    ['0','turquía','{"code":"TR","iso3":"TUR","name":"Turkey"}'],
    ['0','tuvalu','{"code":"TV","iso3":"TUV","name":"Tuvalu"}'],
    ['0','ucrania','{"code":"UA","iso3":"UKR","name":"Ukraine"}'],
    ['0','uganda','{"code":"UG","iso3":"UGA","name":"Uganda"}'],
    ['0','uruguay','{"code":"UY","iso3":"URY","name":"Uruguay"}'],
    ['0','uzbekistán','{"code":"UZ","iso3":"UZB","name":"Uzbekistan"}'],
    ['0','vanuatu','{"code":"VU","iso3":"VUT","name":"Vanuatu"}'],
    ['0','venezuela','{"code":"VE","iso3":"VEN","name":"Venezuela"}'],
    ['0','vietnam','{"code":"VN","iso3":"VNM","name":"Vietnam"}'],
    ['0','wallis y futuna','{"code":"WF","iso3":"WLF","name":"Wallis and Futuna"}'],
    ['0','yemen','{"code":"YE","iso3":"YEM","name":"Yemen"}'],
    ['0','yibuti','{"code":"DJ","iso3":"DJI","name":"Djibouti"}'],
    ['0','zambia','{"code":"ZM","iso3":"ZMB","name":"Zambia"}'],
    ['0','zimbabue','{"code":"ZW","iso3":"ZWE","name":"Zimbabwe"}']
];