<?php //Colombia
$country = 'colombia';

$attr = [
	'levels' => [
		2 => 'Departamentos',
		3 => 'Comunas'
	]
];

//Departamentos
$data[2] = [
	['colombia','antioquia',''],
	['colombia','atlantico',''],
	['colombia','d. c. santa fe de bogotá',''],
	['colombia','bolivar',''],
	['colombia','boyaca',''],
	['colombia','caldas',''],
	['colombia','caqueta',''],
	['colombia','cauca',''],
	['colombia','cesar',''],
	['colombia','cordova',''],
	['colombia','cundinamarca',''],
	['colombia','choco',''],
	['colombia','huila',''],
	['colombia','la guajira',''],
	['colombia','magdalena',''],
	['colombia','meta',''],
	['colombia','nariño',''],
	['colombia','norte de santander',''],
	['colombia','quindio',''],
	['colombia','risaralda',''],
	['colombia','santander',''],
	['colombia','sucre',''],
	['colombia','tolima',''],
	['colombia','valle',''],
	['colombia','arauca',''],
	['colombia','casanare',''],
	['colombia','putumayo',''],
	['colombia','san andres',''],
	['colombia','amazonas',''],
	['colombia','guainia',''],
	['colombia','guaviare',''],
	['colombia','vaupes',''],
	['colombia','vichada','']
];

//Municipios
$data[3] = [
	['antioquia','medellin',''],
	['antioquia','abejorral',''],
	['antioquia','abriaqui',''],
	['antioquia','alejandria',''],
	['antioquia','amaga',''],
	['antioquia','amalfi',''],
	['antioquia','andes',''],
	['antioquia','angelopolis',''],
	['antioquia','angostura',''],
	['antioquia','anori',''],
	['antioquia','antioquia',''],
	['antioquia','anza',''],
	['antioquia','apartado',''],
	['antioquia','arboletes',''],
	['antioquia','argelia',''],
	['antioquia','armenia',''],
	['antioquia','barbosa',''],
	['antioquia','belmira',''],
	['antioquia','bello',''],
	['antioquia','betania',''],
	['antioquia','betulia',''],
	['antioquia','bolivar',''],
	['antioquia','briceño',''],
	['antioquia','buritica',''],
	['antioquia','caceres',''],
	['antioquia','caicedo',''],
	['antioquia','caldas',''],
	['antioquia','campamento',''],
	['antioquia','cañasgordas',''],
	['antioquia','caracoli',''],
	['antioquia','caramanta',''],
	['antioquia','carepa',''],
	['antioquia','carmen de viboral',''],
	['antioquia','carolina',''],
	['antioquia','caucasia',''],
	['antioquia','chigorodo',''],
	['antioquia','cisneros',''],
	['antioquia','cocorna',''],
	['antioquia','concepcion',''],
	['antioquia','concordia',''],
	['antioquia','copacabana',''],
	['antioquia','dabeiba',''],
	['antioquia','don matias',''],
	['antioquia','ebejico',''],
	['antioquia','el bagre',''],
	['antioquia','entrerrios',''],
	['antioquia','envigado',''],
	['antioquia','fredonia',''],
	['antioquia','frontino',''],
	['antioquia','giraldo',''],
	['antioquia','girardota',''],
	['antioquia','gomez plata',''],
	['antioquia','granada',''],
	['antioquia','guadalupe',''],
	['antioquia','guarne',''],
	['antioquia','guatape',''],
	['antioquia','heliconia',''],
	['antioquia','hispania',''],
	['antioquia','itagui',''],
	['antioquia','ituango',''],
	['antioquia','jardin',''],
	['antioquia','jerico',''],
	['antioquia','la ceja',''],
	['antioquia','la estrella',''],
	['antioquia','la pintada',''],
	['antioquia','la union',''],
	['antioquia','liborina',''],
	['antioquia','maceo',''],
	['antioquia','marinilla',''],
	['antioquia','montebello',''],
	['antioquia','murindo',''],
	['antioquia','mutata',''],
	['antioquia','nariño',''],
	['antioquia','necocli',''],
	['antioquia','nechi',''],
	['antioquia','olaya',''],
	['antioquia','peñol',''],
	['antioquia','peque',''],
	['antioquia','pueblorrico',''],
	['antioquia','puerto berrio',''],
	['antioquia','puerto nare (la magdalena)',''],
	['antioquia','puerto triunfo',''],
	['antioquia','remedios',''],
	['antioquia','retiro',''],
	['antioquia','rionegro',''],
	['antioquia','sabanalarga',''],
	['antioquia','sabaneta',''],
	['antioquia','salgar',''],
	['antioquia','san andres',''],
	['antioquia','san carlos',''],
	['antioquia','san francisco',''],
	['antioquia','san jeronimo',''],
	['antioquia','san jose de la montaña',''],
	['antioquia','san juan de uraba',''],
	['antioquia','san luis',''],
	['antioquia','san pedro',''],
	['antioquia','san pedro de uraba',''],
	['antioquia','san rafael',''],
	['antioquia','san roque',''],
	['antioquia','san vicente',''],
	['antioquia','santa barbara',''],
	['antioquia','santa rosa de osos',''],
	['antioquia','santo domingo',''],
	['antioquia','santuario',''],
	['antioquia','segovia',''],
	['antioquia','sonson',''],
	['antioquia','sopetran',''],
	['antioquia','tamesis',''],
	['antioquia','taraza',''],
	['antioquia','tarso',''],
	['antioquia','titiribi',''],
	['antioquia','toledo',''],
	['antioquia','turbo',''],
	['antioquia','uramita',''],
	['antioquia','urrao',''],
	['antioquia','valdivia',''],
	['antioquia','valparaiso',''],
	['antioquia','vegachi',''],
	['antioquia','venecia',''],
	['antioquia','vigia del fuerte',''],
	['antioquia','yali',''],
	['antioquia','yarumal',''],
	['antioquia','yolombo',''],
	['antioquia','yondo',''],
	['antioquia','zaragoza',''],
	['atlantico','barranquilla (distrito especial industrial y portuario de barranquilla)',''],
	['atlantico','baranoa',''],
	['atlantico','campo de la cruz',''],
	['atlantico','candelaria',''],
	['atlantico','galapa',''],
	['atlantico','juan de acosta',''],
	['atlantico','luruaco',''],
	['atlantico','malambo',''],
	['atlantico','manati',''],
	['atlantico','palmar de varela',''],
	['atlantico','piojo',''],
	['atlantico','polo nuevo',''],
	['atlantico','ponedera',''],
	['atlantico','puerto colombia',''],
	['atlantico','repelon',''],
	['atlantico','sabanagrande',''],
	['atlantico','sabanalarga',''],
	['atlantico','santa lucia',''],
	['atlantico','santo tomas',''],
	['atlantico','soledad',''],
	['atlantico','suan',''],
	['atlantico','tubara',''],
	['atlantico','usiacuri',''],
	['d. c. santa fe de bogotá','santa fe de bogotá',''],
	['d. c. santa fe de bogotá','usaquen',''],
	['d. c. santa fe de bogotá','chapinero',''],
	['d. c. santa fe de bogotá','santa fe',''],
	['d. c. santa fe de bogotá','san cristobal',''],
	['d. c. santa fe de bogotá','usme',''],
	['d. c. santa fe de bogotá','tunjuelito',''],
	['d. c. santa fe de bogotá','bosa',''],
	['d. c. santa fe de bogotá','kennedy',''],
	['d. c. santa fe de bogotá','fontibon',''],
	['d. c. santa fe de bogotá','engativa',''],
	['d. c. santa fe de bogotá','suba',''],
	['d. c. santa fe de bogotá','barrios unidos',''],
	['d. c. santa fe de bogotá','teusaquillo',''],
	['d. c. santa fe de bogotá','martires',''],
	['d. c. santa fe de bogotá','antonio nariño',''],
	['d. c. santa fe de bogotá','puente aranda',''],
	['d. c. santa fe de bogotá','candelaria',''],
	['d. c. santa fe de bogotá','rafael uribe',''],
	['d. c. santa fe de bogotá','ciudad bolivar',''],
	['d. c. santa fe de bogotá','sumapaz',''],
	['bolivar','cartagena (distrito turistico y cultural de cartagena)',''],
	['bolivar','achi',''],
	['bolivar','altos del rosario',''],
	['bolivar','arenal',''],
	['bolivar','arjona',''],
	['bolivar','arroyohondo',''],
	['bolivar','barranco de loba',''],
	['bolivar','calamar',''],
	['bolivar','cantagallo',''],
	['bolivar','cicuco',''],
	['bolivar','cordoba',''],
	['bolivar','clemencia',''],
	['bolivar','el carmen de bolivar',''],
	['bolivar','el guamo',''],
	['bolivar','el peñon',''],
	['bolivar','hatillo de loba',''],
	['bolivar','magangue',''],
	['bolivar','mahates',''],
	['bolivar','margarita',''],
	['bolivar','maria la baja',''],
	['bolivar','montecristo',''],
	['bolivar','mompos',''],
	['bolivar','morales',''],
	['bolivar','pinillos',''],
	['bolivar','regidor',''],
	['bolivar','rio viejo',''],
	['bolivar','san cristobal',''],
	['bolivar','san estanislao',''],
	['bolivar','san fernando',''],
	['bolivar','san jacinto',''],
	['bolivar','san jacinto del cauca',''],
	['bolivar','san juan nepomuceno',''],
	['bolivar','san martin de loba',''],
	['bolivar','san pablo',''],
	['bolivar','santa catalina',''],
	['bolivar','santa rosa',''],
	['bolivar','santa rosa del sur',''],
	['bolivar','simiti',''],
	['bolivar','soplaviento',''],
	['bolivar','talaigua nuevo',''],
	['bolivar','tiquisio (puerto rico)',''],
	['bolivar','turbaco',''],
	['bolivar','turbana',''],
	['bolivar','villanueva',''],
	['bolivar','zambrano',''],
	['boyaca','tunja',''],
	['boyaca','almeida',''],
	['boyaca','aquitania',''],
	['boyaca','arcabuco',''],
	['boyaca','belen',''],
	['boyaca','berbeo',''],
	['boyaca','beteitiva',''],
	['boyaca','boavita',''],
	['boyaca','boyaca',''],
	['boyaca','briceño',''],
	['boyaca','buenavista',''],
	['boyaca','busbanza',''],
	['boyaca','caldas',''],
	['boyaca','campohermoso',''],
	['boyaca','cerinza',''],
	['boyaca','chinavita',''],
	['boyaca','chiquinquira',''],
	['boyaca','chiscas',''],
	['boyaca','chita',''],
	['boyaca','chitaraque',''],
	['boyaca','chivata',''],
	['boyaca','cienega',''],
	['boyaca','combita',''],
	['boyaca','coper',''],
	['boyaca','corrales',''],
	['boyaca','covarachia',''],
	['boyaca','cubara',''],
	['boyaca','cucaita',''],
	['boyaca','cuitiva',''],
	['boyaca','chiquiza',''],
	['boyaca','chivor',''],
	['boyaca','duitama',''],
	['boyaca','el cocuy',''],
	['boyaca','el espino',''],
	['boyaca','firavitoba',''],
	['boyaca','floresta',''],
	['boyaca','gachantiva',''],
	['boyaca','gameza',''],
	['boyaca','garagoa',''],
	['boyaca','guacamayas',''],
	['boyaca','guateque',''],
	['boyaca','guayata',''],
	['boyaca','guican',''],
	['boyaca','iza',''],
	['boyaca','jenesano',''],
	['boyaca','jerico',''],
	['boyaca','labranzagrande',''],
	['boyaca','la capilla',''],
	['boyaca','la victoria',''],
	['boyaca','la uvita',''],
	['boyaca','villa de leiva',''],
	['boyaca','macanal',''],
	['boyaca','maripi',''],
	['boyaca','miraflores',''],
	['boyaca','mongua',''],
	['boyaca','mongui',''],
	['boyaca','moniquira',''],
	['boyaca','motavita',''],
	['boyaca','muzo',''],
	['boyaca','nobsa',''],
	['boyaca','nuevo colon',''],
	['boyaca','oicata',''],
	['boyaca','otanche',''],
	['boyaca','pachavita',''],
	['boyaca','paez',''],
	['boyaca','paipa',''],
	['boyaca','pajarito',''],
	['boyaca','panqueba',''],
	['boyaca','pauna',''],
	['boyaca','paya',''],
	['boyaca','paz del rio',''],
	['boyaca','pesca',''],
	['boyaca','pisba',''],
	['boyaca','puerto boyaca',''],
	['boyaca','quipama',''],
	['boyaca','ramiriqui',''],
	['boyaca','raquira',''],
	['boyaca','rondon',''],
	['boyaca','saboya',''],
	['boyaca','sachica',''],
	['boyaca','samaca',''],
	['boyaca','san eduardo',''],
	['boyaca','san jose de pare',''],
	['boyaca','san luis de gaceno',''],
	['boyaca','san mateo',''],
	['boyaca','san miguel de sema',''],
	['boyaca','san pablo de borbur',''],
	['boyaca','santana',''],
	['boyaca','santa maria',''],
	['boyaca','santa rosa de viterbo',''],
	['boyaca','santa sofia',''],
	['boyaca','sativanorte',''],
	['boyaca','sativasur',''],
	['boyaca','siachoque',''],
	['boyaca','soata',''],
	['boyaca','socota',''],
	['boyaca','socha',''],
	['boyaca','sogamoso',''],
	['boyaca','somondoco',''],
	['boyaca','sora',''],
	['boyaca','sotaquira',''],
	['boyaca','soraca',''],
	['boyaca','susacon',''],
	['boyaca','sutamarchan',''],
	['boyaca','sutatenza',''],
	['boyaca','tasco',''],
	['boyaca','tenza',''],
	['boyaca','tibana',''],
	['boyaca','tibasosa',''],
	['boyaca','tinjaca',''],
	['boyaca','tipacoque',''],
	['boyaca','toca',''],
	['boyaca','togui',''],
	['boyaca','topaga',''],
	['boyaca','tota',''],
	['boyaca','tunungua',''],
	['boyaca','turmeque',''],
	['boyaca','tuta',''],
	['boyaca','tutasa',''],
	['boyaca','umbita',''],
	['boyaca','ventaquemada',''],
	['boyaca','viracacha',''],
	['boyaca','zetaquira',''],
	['caldas','manizales',''],
	['caldas','aguadas',''],
	['caldas','anserma',''],
	['caldas','aranzazu',''],
	['caldas','belalcazar',''],
	['caldas','chinchina',''],
	['caldas','filadelfia',''],
	['caldas','la dorada',''],
	['caldas','la merced',''],
	['caldas','manzanares',''],
	['caldas','marmato',''],
	['caldas','marquetalia',''],
	['caldas','marulanda',''],
	['caldas','neira',''],
	['caldas','norcasia',''],
	['caldas','pacora',''],
	['caldas','palestina',''],
	['caldas','pensilvania',''],
	['caldas','riosucio',''],
	['caldas','risaralda',''],
	['caldas','salamina',''],
	['caldas','samana',''],
	['caldas','san jose',''],
	['caldas','supia',''],
	['caldas','victoria',''],
	['caldas','villamaria',''],
	['caldas','viterbo',''],
	['caqueta','florencia',''],
	['caqueta','albania',''],
	['caqueta','belen de los andaquies',''],
	['caqueta','cartagena del chaira',''],
	['caqueta','curillo',''],
	['caqueta','el doncello',''],
	['caqueta','el paujil',''],
	['caqueta','la montañita',''],
	['caqueta','milan',''],
	['caqueta','morelia',''],
	['caqueta','puerto rico',''],
	['caqueta','san jose de fragua',''],
	['caqueta','san vicente del caguan',''],
	['caqueta','solano',''],
	['caqueta','solita',''],
	['caqueta','valparaiso',''],
	['cauca','popayan',''],
	['cauca','almaguer',''],
	['cauca','argelia',''],
	['cauca','balboa',''],
	['cauca','bolivar',''],
	['cauca','buenos aires',''],
	['cauca','cajibio',''],
	['cauca','caldono',''],
	['cauca','caloto',''],
	['cauca','corinto',''],
	['cauca','el tambo',''],
	['cauca','florencia',''],
	['cauca','guapi',''],
	['cauca','inza',''],
	['cauca','jambalo',''],
	['cauca','la sierra',''],
	['cauca','la vega',''],
	['cauca','lopez (micay)',''],
	['cauca','mercaderes',''],
	['cauca','miranda',''],
	['cauca','morales',''],
	['cauca','padilla',''],
	['cauca','paez (belalcazar)',''],
	['cauca','patia (el bordo)',''],
	['cauca','piamonte',''],
	['cauca','piendamo',''],
	['cauca','puerto tejada',''],
	['cauca','purace (coconuco)',''],
	['cauca','rosas',''],
	['cauca','san sebastian',''],
	['cauca','santander de quilichao',''],
	['cauca','santa rosa',''],
	['cauca','silvia',''],
	['cauca','sotara (paispamba)',''],
	['cauca','suarez',''],
	['cauca','timbio',''],
	['cauca','timbiqui',''],
	['cauca','toribio',''],
	['cauca','totoro',''],
	['cauca','villarica',''],
	['cesar','valledupar',''],
	['cesar','aguachica',''],
	['cesar','agustin codazzi',''],
	['cesar','astrea',''],
	['cesar','becerril',''],
	['cesar','bosconia',''],
	['cesar','chimichagua',''],
	['cesar','chiriguana',''],
	['cesar','curumani',''],
	['cesar','el copey',''],
	['cesar','el paso',''],
	['cesar','gamarra',''],
	['cesar','gonzalez',''],
	['cesar','la gloria',''],
	['cesar','la jagua ibirico',''],
	['cesar','manaure (balcon del cesar)',''],
	['cesar','pailitas',''],
	['cesar','pelaya',''],
	['cesar','pueblo bello',''],
	['cesar','rio de oro',''],
	['cesar','la paz (robles)',''],
	['cesar','san alberto',''],
	['cesar','san diego',''],
	['cesar','san martin',''],
	['cesar','tamalameque',''],
	['cordova','monteria',''],
	['cordova','ayapel',''],
	['cordova','buenavista',''],
	['cordova','canalete',''],
	['cordova','cerete',''],
	['cordova','chima',''],
	['cordova','chinu',''],
	['cordova','cienaga de oro',''],
	['cordova','cotorra',''],
	['cordova','la apartada',''],
	['cordova','lorica',''],
	['cordova','los cordobas',''],
	['cordova','momil',''],
	['cordova','montelibano',''],
	['cordova','moñitos',''],
	['cordova','planeta rica',''],
	['cordova','pueblo nuevo',''],
	['cordova','puerto escondido',''],
	['cordova','puerto libertador',''],
	['cordova','purisima',''],
	['cordova','sahagun',''],
	['cordova','san andres sotavento',''],
	['cordova','san antero',''],
	['cordova','san bernardo del viento',''],
	['cordova','san carlos',''],
	['cordova','san pelayo',''],
	['cordova','tierralta',''],
	['cordova','valencia',''],
	['cundinamarca','agua de dios',''],
	['cundinamarca','alban',''],
	['cundinamarca','anapoima',''],
	['cundinamarca','anolaima',''],
	['cundinamarca','arbelaez',''],
	['cundinamarca','beltran',''],
	['cundinamarca','bituima',''],
	['cundinamarca','bojaca',''],
	['cundinamarca','cabrera',''],
	['cundinamarca','cachipay',''],
	['cundinamarca','cajica',''],
	['cundinamarca','caparrapi',''],
	['cundinamarca','caqueza',''],
	['cundinamarca','carmen de carupa',''],
	['cundinamarca','chaguani',''],
	['cundinamarca','chia',''],
	['cundinamarca','chipaque',''],
	['cundinamarca','choachi',''],
	['cundinamarca','choconta',''],
	['cundinamarca','cogua',''],
	['cundinamarca','cota',''],
	['cundinamarca','cucunuba',''],
	['cundinamarca','el colegio',''],
	['cundinamarca','el peñon',''],
	['cundinamarca','el rosal',''],
	['cundinamarca','facatativa',''],
	['cundinamarca','fomeque',''],
	['cundinamarca','fosca',''],
	['cundinamarca','funza',''],
	['cundinamarca','fuquene',''],
	['cundinamarca','fusagasuga',''],
	['cundinamarca','gachala',''],
	['cundinamarca','gachancipa',''],
	['cundinamarca','gacheta',''],
	['cundinamarca','gama',''],
	['cundinamarca','girardot',''],
	['cundinamarca','granada',''],
	['cundinamarca','guacheta',''],
	['cundinamarca','guaduas',''],
	['cundinamarca','guasca',''],
	['cundinamarca','guataqui',''],
	['cundinamarca','guatavita',''],
	['cundinamarca','guayabal de siquima',''],
	['cundinamarca','guayabetal',''],
	['cundinamarca','gutierrez',''],
	['cundinamarca','jerusalen',''],
	['cundinamarca','junin',''],
	['cundinamarca','la calera',''],
	['cundinamarca','la mesa',''],
	['cundinamarca','la palma',''],
	['cundinamarca','la peña',''],
	['cundinamarca','la vega',''],
	['cundinamarca','lenguazaque',''],
	['cundinamarca','macheta',''],
	['cundinamarca','madrid',''],
	['cundinamarca','manta',''],
	['cundinamarca','medina',''],
	['cundinamarca','mosquera',''],
	['cundinamarca','nariño',''],
	['cundinamarca','nemocon',''],
	['cundinamarca','nilo',''],
	['cundinamarca','nimaima',''],
	['cundinamarca','nocaima',''],
	['cundinamarca','venecia (ospina perez)',''],
	['cundinamarca','pacho',''],
	['cundinamarca','paime',''],
	['cundinamarca','pandi',''],
	['cundinamarca','paratebueno',''],
	['cundinamarca','pasca',''],
	['cundinamarca','puerto salgar',''],
	['cundinamarca','puli',''],
	['cundinamarca','quebradanegra',''],
	['cundinamarca','quetame',''],
	['cundinamarca','quipile',''],
	['cundinamarca','apulo (rafael reyes)',''],
	['cundinamarca','ricaurte',''],
	['cundinamarca','san antonio del tequendama',''],
	['cundinamarca','san bernardo',''],
	['cundinamarca','san cayetano',''],
	['cundinamarca','san francisco',''],
	['cundinamarca','san juan de rioseco',''],
	['cundinamarca','sasaima',''],
	['cundinamarca','sesquile',''],
	['cundinamarca','sibate',''],
	['cundinamarca','silvania',''],
	['cundinamarca','simijaca',''],
	['cundinamarca','soacha',''],
	['cundinamarca','sopo',''],
	['cundinamarca','subachoque',''],
	['cundinamarca','suesca',''],
	['cundinamarca','supata',''],
	['cundinamarca','susa',''],
	['cundinamarca','sutatausa',''],
	['cundinamarca','tabio',''],
	['cundinamarca','tausa',''],
	['cundinamarca','tena',''],
	['cundinamarca','tenjo',''],
	['cundinamarca','tibacuy',''],
	['cundinamarca','tibirita',''],
	['cundinamarca','tocaima',''],
	['cundinamarca','tocancipa',''],
	['cundinamarca','topaipi',''],
	['cundinamarca','ubala',''],
	['cundinamarca','ubaque',''],
	['cundinamarca','ubate',''],
	['cundinamarca','une',''],
	['cundinamarca','utica',''],
	['cundinamarca','vergara',''],
	['cundinamarca','viani',''],
	['cundinamarca','villagomez',''],
	['cundinamarca','villapinzon',''],
	['cundinamarca','villeta',''],
	['cundinamarca','viota',''],
	['cundinamarca','yacopi',''],
	['cundinamarca','zipacon',''],
	['cundinamarca','zipaquira',''],
	['choco','quibdo (san francisco de quibdo)',''],
	['choco','acandi',''],
	['choco','alto baudo (pie de pato)',''],
	['choco','atrato',''],
	['choco','bagado',''],
	['choco','bahia solano (mutis)',''],
	['choco','bajo baudo (pizarro)',''],
	['choco','bojaya (bellavista)',''],
	['choco','canton de san pablo (managru)',''],
	['choco','condoto',''],
	['choco','el carmen de atrato',''],
	['choco','litoral del bajo san juan (santa genoveva de docordo)',''],
	['choco','istmina',''],
	['choco','jurado',''],
	['choco','lloro',''],
	['choco','medio atrato',''],
	['choco','medio baudo',''],
	['choco','novita',''],
	['choco','nuqui',''],
	['choco','rioquito',''],
	['choco','riosucio',''],
	['choco','san jose del palmar',''],
	['choco','sipi',''],
	['choco','tado',''],
	['choco','unguia',''],
	['choco','union panamericana',''],
	['huila','neiva',''],
	['huila','acevedo',''],
	['huila','agrado',''],
	['huila','aipe',''],
	['huila','algeciras',''],
	['huila','altamira',''],
	['huila','baraya',''],
	['huila','campoalegre',''],
	['huila','colombia',''],
	['huila','elias',''],
	['huila','garzon',''],
	['huila','gigante',''],
	['huila','guadalupe',''],
	['huila','hobo',''],
	['huila','iquira',''],
	['huila','isnos (san jose de isnos)',''],
	['huila','la argentina',''],
	['huila','la plata',''],
	['huila','nataga',''],
	['huila','oporapa',''],
	['huila','paicol',''],
	['huila','palermo',''],
	['huila','palestina',''],
	['huila','pital',''],
	['huila','pitalito',''],
	['huila','rivera',''],
	['huila','saladoblanco',''],
	['huila','san agustin',''],
	['huila','santa maria',''],
	['huila','suaza',''],
	['huila','tarqui',''],
	['huila','tesalia',''],
	['huila','tello',''],
	['huila','teruel',''],
	['huila','timana',''],
	['huila','villavieja',''],
	['huila','yaguara',''],
	['la guajira','riohacha',''],
	['la guajira','barrancas',''],
	['la guajira','dibulla',''],
	['la guajira','distraccion',''],
	['la guajira','el molino',''],
	['la guajira','fonseca',''],
	['la guajira','hatonuevo',''],
	['la guajira','la jagua del pilar',''],
	['la guajira','maicao',''],
	['la guajira','manaure',''],
	['la guajira','san juan del cesar',''],
	['la guajira','uribia',''],
	['la guajira','urumita',''],
	['la guajira','villanueva',''],
	['magdalena','santa marta (distrito turistico cultural e historico de santa marta)',''],
	['magdalena','algarrobo',''],
	['magdalena','aracataca',''],
	['magdalena','ariguani (el dificil)',''],
	['magdalena','cerro san antonio',''],
	['magdalena','chivolo',''],
	['magdalena','cienaga',''],
	['magdalena','concordia',''],
	['magdalena','el banco',''],
	['magdalena','el piñon',''],
	['magdalena','el reten',''],
	['magdalena','fundacion',''],
	['magdalena','guamal',''],
	['magdalena','pedraza',''],
	['magdalena','pijiño del carmen (pijiño)',''],
	['magdalena','pivijay',''],
	['magdalena','plato',''],
	['magdalena','puebloviejo',''],
	['magdalena','remolino',''],
	['magdalena','sabanas de san angel',''],
	['magdalena','salamina',''],
	['magdalena','san sebastian de buenavista',''],
	['magdalena','san zenon',''],
	['magdalena','santa ana',''],
	['magdalena','sitionuevo',''],
	['magdalena','tenerife',''],
	['meta','villavicencio',''],
	['meta','acacias',''],
	['meta','barranca de upia',''],
	['meta','cabuyaro',''],
	['meta','castilla la nueva',''],
	['meta','san luis de cubarral',''],
	['meta','cumaral',''],
	['meta','el calvario',''],
	['meta','el castillo',''],
	['meta','el dorado',''],
	['meta','fuente de oro',''],
	['meta','granada',''],
	['meta','guamal',''],
	['meta','mapiripan',''],
	['meta','mesetas',''],
	['meta','la macarena',''],
	['meta','la uribe',''],
	['meta','lejanias',''],
	['meta','puerto concordia',''],
	['meta','puerto gaitan',''],
	['meta','puerto lopez',''],
	['meta','puerto lleras',''],
	['meta','puerto rico',''],
	['meta','restrepo',''],
	['meta','san carlos de guaroa',''],
	['meta','san juan de arama',''],
	['meta','san juanito',''],
	['meta','san martin',''],
	['meta','vistahermosa',''],
	['nariño','pasto (san juan de pasto)',''],
	['nariño','alban (san jose)',''],
	['nariño','aldana',''],
	['nariño','ancuya',''],
	['nariño','arboleda (berruecos)',''],
	['nariño','barbacoas',''],
	['nariño','belen',''],
	['nariño','buesaco',''],
	['nariño','colon (genova)',''],
	['nariño','consaca',''],
	['nariño','contadero',''],
	['nariño','cordoba',''],
	['nariño','cuaspud (carlosama)',''],
	['nariño','cumbal',''],
	['nariño','cumbitara',''],
	['nariño','chachagui',''],
	['nariño','el charco',''],
	['nariño','el peñol',''],
	['nariño','el rosario',''],
	['nariño','el tablon',''],
	['nariño','el tambo',''],
	['nariño','funes',''],
	['nariño','guachucal',''],
	['nariño','guaitarilla',''],
	['nariño','gualmatan',''],
	['nariño','iles',''],
	['nariño','imues',''],
	['nariño','ipiales',''],
	['nariño','la cruz',''],
	['nariño','la florida',''],
	['nariño','la llanada',''],
	['nariño','la tola',''],
	['nariño','la union',''],
	['nariño','leiva',''],
	['nariño','linares',''],
	['nariño','los andes (sotomayor)',''],
	['nariño','magui (payan)',''],
	['nariño','mallama (piedrancha)',''],
	['nariño','mosquera',''],
	['nariño','olaya herrera (bocas de satinga)',''],
	['nariño','ospina',''],
	['nariño','francisco pizarro (salahonda)',''],
	['nariño','policarpa',''],
	['nariño','potosi',''],
	['nariño','providencia',''],
	['nariño','puerres',''],
	['nariño','pupiales',''],
	['nariño','ricaurte',''],
	['nariño','roberto payan (san jose)',''],
	['nariño','samaniego',''],
	['nariño','sandona',''],
	['nariño','san bernardo',''],
	['nariño','san lorenzo',''],
	['nariño','san pablo',''],
	['nariño','san pedro de cartago',''],
	['nariño','santa barbara (iscuande)',''],
	['nariño','santa cruz (guachaves)',''],
	['nariño','sapuyes',''],
	['nariño','taminango',''],
	['nariño','tangua',''],
	['nariño','tumaco',''],
	['nariño','tuquerres',''],
	['nariño','yacuanquer',''],
	['norte de santander','cucuta',''],
	['norte de santander','abrego',''],
	['norte de santander','arboledas',''],
	['norte de santander','bochalema',''],
	['norte de santander','bucarasica',''],
	['norte de santander','cacota',''],
	['norte de santander','cachira',''],
	['norte de santander','chinacota',''],
	['norte de santander','chitaga',''],
	['norte de santander','convencion',''],
	['norte de santander','cucutilla',''],
	['norte de santander','durania',''],
	['norte de santander','el carmen',''],
	['norte de santander','el tarra',''],
	['norte de santander','el zulia',''],
	['norte de santander','gramalote',''],
	['norte de santander','hacari',''],
	['norte de santander','herran',''],
	['norte de santander','labateca',''],
	['norte de santander','la esperanza',''],
	['norte de santander','la playa',''],
	['norte de santander','los patios',''],
	['norte de santander','lourdes',''],
	['norte de santander','mutiscua',''],
	['norte de santander','ocaña',''],
	['norte de santander','pamplona',''],
	['norte de santander','pamplonita',''],
	['norte de santander','puerto santander',''],
	['norte de santander','ragonvalia',''],
	['norte de santander','salazar',''],
	['norte de santander','san calixto',''],
	['norte de santander','san cayetano',''],
	['norte de santander','santiago',''],
	['norte de santander','sardinata',''],
	['norte de santander','silos',''],
	['norte de santander','teorama',''],
	['norte de santander','tibu',''],
	['norte de santander','toledo',''],
	['norte de santander','villacaro',''],
	['norte de santander','villa del rosario',''],
	['quindio','armenia',''],
	['quindio','buenavista',''],
	['quindio','calarca',''],
	['quindio','circasia',''],
	['quindio','cordoba',''],
	['quindio','filandia',''],
	['quindio','genova',''],
	['quindio','la tebaida',''],
	['quindio','montenegro',''],
	['quindio','pijao',''],
	['quindio','quimbaya',''],
	['quindio','salento',''],
	['risaralda','pereira',''],
	['risaralda','apia',''],
	['risaralda','balboa',''],
	['risaralda','belen de umbria',''],
	['risaralda','dos quebradas',''],
	['risaralda','guatica',''],
	['risaralda','la celia',''],
	['risaralda','la virginia',''],
	['risaralda','marsella',''],
	['risaralda','mistrato',''],
	['risaralda','pueblo rico',''],
	['risaralda','quinchia',''],
	['risaralda','santa rosa de cabal',''],
	['risaralda','santuario',''],
	['santander','bucaramanga',''],
	['santander','aguada',''],
	['santander','albania',''],
	['santander','aratoca',''],
	['santander','barbosa',''],
	['santander','barichara',''],
	['santander','barrancabermeja',''],
	['santander','betulia',''],
	['santander','bolivar',''],
	['santander','cabrera',''],
	['santander','california',''],
	['santander','capitanejo',''],
	['santander','carcasi',''],
	['santander','cepita',''],
	['santander','cerrito',''],
	['santander','charala',''],
	['santander','charta',''],
	['santander','chima',''],
	['santander','chipata',''],
	['santander','cimitarra',''],
	['santander','concepcion',''],
	['santander','confines',''],
	['santander','contratacion',''],
	['santander','coromoro',''],
	['santander','curiti',''],
	['santander','el carmen de chucury',''],
	['santander','el guacamayo',''],
	['santander','el peñon',''],
	['santander','el playon',''],
	['santander','encino',''],
	['santander','enciso',''],
	['santander','florian',''],
	['santander','floridablanca',''],
	['santander','galan',''],
	['santander','gambita',''],
	['santander','giron',''],
	['santander','guaca',''],
	['santander','guadalupe',''],
	['santander','guapota',''],
	['santander','guavata',''],
	['santander','guepsa',''],
	['santander','hato',''],
	['santander','jesus maria',''],
	['santander','jordan',''],
	['santander','la belleza',''],
	['santander','landazuri',''],
	['santander','la paz',''],
	['santander','lebrija',''],
	['santander','los santos',''],
	['santander','macaravita',''],
	['santander','malaga',''],
	['santander','matanza',''],
	['santander','mogotes',''],
	['santander','molagavita',''],
	['santander','ocamonte',''],
	['santander','oiba',''],
	['santander','onzaga',''],
	['santander','palmar',''],
	['santander','palmas del socorro',''],
	['santander','paramo',''],
	['santander','piedecuesta',''],
	['santander','pinchote',''],
	['santander','puente nacional',''],
	['santander','puerto parra',''],
	['santander','puerto wilches',''],
	['santander','rionegro',''],
	['santander','sabana de torres',''],
	['santander','san andres',''],
	['santander','san benito',''],
	['santander','san gil',''],
	['santander','san joaquin',''],
	['santander','san jose de miranda',''],
	['santander','san miguel',''],
	['santander','san vicente de chucuri',''],
	['santander','santa barbara',''],
	['santander','santa helena del opon',''],
	['santander','simacota',''],
	['santander','socorro',''],
	['santander','suaita',''],
	['santander','sucre',''],
	['santander','surata',''],
	['santander','tona',''],
	['santander','valle san jose',''],
	['santander','velez',''],
	['santander','vetas',''],
	['santander','villanueva',''],
	['santander','zapatoca',''],
	['sucre','sincelejo',''],
	['sucre','buenavista',''],
	['sucre','caimito',''],
	['sucre','coloso (ricaurte)',''],
	['sucre','corozal',''],
	['sucre','chalan',''],
	['sucre','galeras (nueva granada)',''],
	['sucre','guaranda',''],
	['sucre','la union',''],
	['sucre','los palmitos',''],
	['sucre','majagual',''],
	['sucre','morroa',''],
	['sucre','ovejas',''],
	['sucre','palmito',''],
	['sucre','sampues',''],
	['sucre','san benito abad',''],
	['sucre','san juan de betulia',''],
	['sucre','san marcos',''],
	['sucre','san onofre',''],
	['sucre','san pedro',''],
	['sucre','since',''],
	['sucre','sucre',''],
	['sucre','tolu',''],
	['sucre','toluviejo',''],
	['tolima','ibague',''],
	['tolima','alpujarra',''],
	['tolima','alvarado',''],
	['tolima','ambalema',''],
	['tolima','anzoategui',''],
	['tolima','armero (guayabal)',''],
	['tolima','ataco',''],
	['tolima','cajamarca',''],
	['tolima','carmen apicala',''],
	['tolima','casabianca',''],
	['tolima','chaparral',''],
	['tolima','coello',''],
	['tolima','coyaima',''],
	['tolima','cunday',''],
	['tolima','dolores',''],
	['tolima','espinal',''],
	['tolima','falan',''],
	['tolima','flandes',''],
	['tolima','fresno',''],
	['tolima','guamo',''],
	['tolima','herveo',''],
	['tolima','honda',''],
	['tolima','icononzo',''],
	['tolima','lerida',''],
	['tolima','libano',''],
	['tolima','mariquita',''],
	['tolima','melgar',''],
	['tolima','murillo',''],
	['tolima','natagaima',''],
	['tolima','ortega',''],
	['tolima','palocabildo',''],
	['tolima','piedras',''],
	['tolima','planadas',''],
	['tolima','prado',''],
	['tolima','purificacion',''],
	['tolima','rioblanco',''],
	['tolima','roncesvalles',''],
	['tolima','rovira',''],
	['tolima','saldaña',''],
	['tolima','san antonio',''],
	['tolima','san luis',''],
	['tolima','santa isabel',''],
	['tolima','suarez',''],
	['tolima','valle de san juan',''],
	['tolima','venadillo',''],
	['tolima','villahermosa',''],
	['tolima','villarrica',''],
	['valle','cali (santiago de cali)',''],
	['valle','alcala',''],
	['valle','andalucia',''],
	['valle','ansermanuevo',''],
	['valle','argelia',''],
	['valle','bolivar',''],
	['valle','buenaventura',''],
	['valle','buga',''],
	['valle','bugalagrande',''],
	['valle','caicedonia',''],
	['valle','calima (darien)',''],
	['valle','candelaria',''],
	['valle','cartago',''],
	['valle','dagua',''],
	['valle','el aguila',''],
	['valle','el cairo',''],
	['valle','el cerrito',''],
	['valle','el dovio',''],
	['valle','florida',''],
	['valle','ginebra',''],
	['valle','guacari',''],
	['valle','jamundi',''],
	['valle','la cumbre',''],
	['valle','la union',''],
	['valle','la victoria',''],
	['valle','obando',''],
	['valle','palmira',''],
	['valle','pradera',''],
	['valle','restrepo',''],
	['valle','riofrio',''],
	['valle','roldanillo',''],
	['valle','san pedro',''],
	['valle','sevilla',''],
	['valle','toro',''],
	['valle','trujillo',''],
	['valle','tulua',''],
	['valle','ulloa',''],
	['valle','versalles',''],
	['valle','vijes',''],
	['valle','yotoco',''],
	['valle','yumbo',''],
	['valle','zarzal',''],
	['arauca','arauca',''],
	['arauca','arauquita',''],
	['arauca','cravo norte',''],
	['arauca','fortul',''],
	['arauca','puerto rondon',''],
	['arauca','saravena',''],
	['arauca','tame',''],
	['casanare','yopal',''],
	['casanare','aguazul',''],
	['casanare','chameza',''],
	['casanare','hato corozal',''],
	['casanare','la salina',''],
	['casanare','mani',''],
	['casanare','monterrey',''],
	['casanare','nunchia',''],
	['casanare','orocue',''],
	['casanare','paz de ariporo',''],
	['casanare','pore',''],
	['casanare','recetor',''],
	['casanare','sabanalarga',''],
	['casanare','sacama',''],
	['casanare','san luis de palenque',''],
	['casanare','tamara',''],
	['casanare','tauramena',''],
	['casanare','trinidad',''],
	['casanare','villanueva',''],
	['putumayo','mocoa',''],
	['putumayo','colon',''],
	['putumayo','orito',''],
	['putumayo','puerto asis',''],
	['putumayo','puerto caicedo',''],
	['putumayo','puerto guzman',''],
	['putumayo','puerto leguizamo',''],
	['putumayo','sibundoy',''],
	['putumayo','san francisco',''],
	['putumayo','san miguel (la dorada)',''],
	['putumayo','santiago',''],
	['putumayo','la hormiga (valle del guamuez)',''],
	['putumayo','villagarzon',''],
	['san andres','san andres',''],
	['san andres','providencia',''],
	['amazonas','leticia',''],
	['amazonas','el encanto',''],
	['amazonas','la chorrera',''],
	['amazonas','la pedrera',''],
	['amazonas','la victoria',''],
	['amazonas','miriti-parana',''],
	['amazonas','puerto alegria',''],
	['amazonas','puerto arica',''],
	['amazonas','puerto nariño',''],
	['amazonas','puerto santander',''],
	['amazonas','tarapaca',''],
	['guainia','puerto inirida',''],
	['guainia','barranco minas',''],
	['guainia','san felipe',''],
	['guainia','puerto colombia',''],
	['guainia','la guadalupe',''],
	['guainia','cacahual',''],
	['guainia','pana pana (campo alegre)',''],
	['guainia','morichal (morichal nuevo)',''],
	['guaviare','san jose del guaviare',''],
	['guaviare','calamar',''],
	['guaviare','el retorno',''],
	['guaviare','miraflores',''],
	['vaupes','mitu',''],
	['vaupes','caruru',''],
	['vaupes','pacoa',''],
	['vaupes','taraira',''],
	['vaupes','papunaua (morichal)',''],
	['vaupes','yavarate',''],
	['vichada','puerto carreño',''],
	['vichada','la primavera',''],
	['vichada','santa rita',''],
	['vichada','santa rosalia',''],
	['vichada','san jose de ocune',''],
	['vichada','cumaribo','']
];